// Code generated by ent, DO NOT EDIT.

package subscriptionplangroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionplangroup type in the database.
	Label = "subscription_plan_group"
	// FieldSubscriptionPlanID holds the string denoting the subscription_plan_id field in the database.
	FieldSubscriptionPlanID = "subscription_plan_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSubscriptionPlan holds the string denoting the subscription_plan edge name in mutations.
	EdgeSubscriptionPlan = "subscription_plan"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// SubscriptionPlanFieldID holds the string denoting the ID field of the SubscriptionPlan.
	SubscriptionPlanFieldID = "id"
	// GroupFieldID holds the string denoting the ID field of the Group.
	GroupFieldID = "id"
	// Table holds the table name of the subscriptionplangroup in the database.
	Table = "subscription_plan_groups"
	// SubscriptionPlanTable is the table that holds the subscription_plan relation/edge.
	SubscriptionPlanTable = "subscription_plan_groups"
	// SubscriptionPlanInverseTable is the table name for the SubscriptionPlan entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionplan" package.
	SubscriptionPlanInverseTable = "subscription_plans"
	// SubscriptionPlanColumn is the table column denoting the subscription_plan relation/edge.
	SubscriptionPlanColumn = "subscription_plan_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "subscription_plan_groups"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for subscriptionplangroup fields.
var Columns = []string{
	FieldSubscriptionPlanID,
	FieldGroupID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionPlanGroup queries.
type OrderOption func(*sql.Selector)

// BySubscriptionPlanID orders the results by the subscription_plan_id field.
func BySubscriptionPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionPlanID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySubscriptionPlanField orders the results by subscription_plan field.
func BySubscriptionPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriptionPlanStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newSubscriptionPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, SubscriptionPlanColumn),
		sqlgraph.To(SubscriptionPlanInverseTable, SubscriptionPlanFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SubscriptionPlanTable, SubscriptionPlanColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, GroupColumn),
		sqlgraph.To(GroupInverseTable, GroupFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
