// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/datasharesession"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// DataShareSessionUpdate is the builder for updating DataShareSession entities.
type DataShareSessionUpdate struct {
	config
	hooks    []Hook
	mutation *DataShareSessionMutation
}

// Where appends a list predicates to the DataShareSessionUpdate builder.
func (_u *DataShareSessionUpdate) Where(ps ...predicate.DataShareSession) *DataShareSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTrajectoryID sets the "trajectory_id" field.
func (_u *DataShareSessionUpdate) SetTrajectoryID(v string) *DataShareSessionUpdate {
	_u.mutation.SetTrajectoryID(v)
	return _u
}

// SetNillableTrajectoryID sets the "trajectory_id" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableTrajectoryID(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetTrajectoryID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *DataShareSessionUpdate) SetSessionID(v string) *DataShareSessionUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableSessionID(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetDataset sets the "dataset" field.
func (_u *DataShareSessionUpdate) SetDataset(v string) *DataShareSessionUpdate {
	_u.mutation.SetDataset(v)
	return _u
}

// SetNillableDataset sets the "dataset" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableDataset(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetDataset(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *DataShareSessionUpdate) SetProvider(v string) *DataShareSessionUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableProvider(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *DataShareSessionUpdate) SetModel(v string) *DataShareSessionUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableModel(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *DataShareSessionUpdate) SetRequestPath(v string) *DataShareSessionUpdate {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableRequestPath(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *DataShareSessionUpdate) SetUserAgent(v string) *DataShareSessionUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableUserAgent(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DataShareSessionUpdate) SetStatus(v string) *DataShareSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableStatus(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsFinalSnapshot sets the "is_final_snapshot" field.
func (_u *DataShareSessionUpdate) SetIsFinalSnapshot(v bool) *DataShareSessionUpdate {
	_u.mutation.SetIsFinalSnapshot(v)
	return _u
}

// SetNillableIsFinalSnapshot sets the "is_final_snapshot" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableIsFinalSnapshot(v *bool) *DataShareSessionUpdate {
	if v != nil {
		_u.SetIsFinalSnapshot(*v)
	}
	return _u
}

// SetSourceRequestCount sets the "source_request_count" field.
func (_u *DataShareSessionUpdate) SetSourceRequestCount(v int) *DataShareSessionUpdate {
	_u.mutation.ResetSourceRequestCount()
	_u.mutation.SetSourceRequestCount(v)
	return _u
}

// SetNillableSourceRequestCount sets the "source_request_count" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableSourceRequestCount(v *int) *DataShareSessionUpdate {
	if v != nil {
		_u.SetSourceRequestCount(*v)
	}
	return _u
}

// AddSourceRequestCount adds value to the "source_request_count" field.
func (_u *DataShareSessionUpdate) AddSourceRequestCount(v int) *DataShareSessionUpdate {
	_u.mutation.AddSourceRequestCount(v)
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *DataShareSessionUpdate) SetSystemPrompt(v string) *DataShareSessionUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableSystemPrompt(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *DataShareSessionUpdate) ClearSystemPrompt() *DataShareSessionUpdate {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetTools sets the "tools" field.
func (_u *DataShareSessionUpdate) SetTools(v []map[string]interface{}) *DataShareSessionUpdate {
	_u.mutation.SetTools(v)
	return _u
}

// AppendTools appends value to the "tools" field.
func (_u *DataShareSessionUpdate) AppendTools(v []map[string]interface{}) *DataShareSessionUpdate {
	_u.mutation.AppendTools(v)
	return _u
}

// ClearTools clears the value of the "tools" field.
func (_u *DataShareSessionUpdate) ClearTools() *DataShareSessionUpdate {
	_u.mutation.ClearTools()
	return _u
}

// SetMessages sets the "messages" field.
func (_u *DataShareSessionUpdate) SetMessages(v []map[string]interface{}) *DataShareSessionUpdate {
	_u.mutation.SetMessages(v)
	return _u
}

// AppendMessages appends value to the "messages" field.
func (_u *DataShareSessionUpdate) AppendMessages(v []map[string]interface{}) *DataShareSessionUpdate {
	_u.mutation.AppendMessages(v)
	return _u
}

// ClearMessages clears the value of the "messages" field.
func (_u *DataShareSessionUpdate) ClearMessages() *DataShareSessionUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// SetUsage sets the "usage" field.
func (_u *DataShareSessionUpdate) SetUsage(v map[string]interface{}) *DataShareSessionUpdate {
	_u.mutation.SetUsage(v)
	return _u
}

// ClearUsage clears the value of the "usage" field.
func (_u *DataShareSessionUpdate) ClearUsage() *DataShareSessionUpdate {
	_u.mutation.ClearUsage()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *DataShareSessionUpdate) SetMeta(v map[string]interface{}) *DataShareSessionUpdate {
	_u.mutation.SetMeta(v)
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *DataShareSessionUpdate) ClearMeta() *DataShareSessionUpdate {
	_u.mutation.ClearMeta()
	return _u
}

// SetSessionJSON sets the "session_json" field.
func (_u *DataShareSessionUpdate) SetSessionJSON(v map[string]interface{}) *DataShareSessionUpdate {
	_u.mutation.SetSessionJSON(v)
	return _u
}

// ClearSessionJSON clears the value of the "session_json" field.
func (_u *DataShareSessionUpdate) ClearSessionJSON() *DataShareSessionUpdate {
	_u.mutation.ClearSessionJSON()
	return _u
}

// SetPayloadCompressed sets the "payload_compressed" field.
func (_u *DataShareSessionUpdate) SetPayloadCompressed(v []byte) *DataShareSessionUpdate {
	_u.mutation.SetPayloadCompressed(v)
	return _u
}

// ClearPayloadCompressed clears the value of the "payload_compressed" field.
func (_u *DataShareSessionUpdate) ClearPayloadCompressed() *DataShareSessionUpdate {
	_u.mutation.ClearPayloadCompressed()
	return _u
}

// SetPayloadEncoding sets the "payload_encoding" field.
func (_u *DataShareSessionUpdate) SetPayloadEncoding(v string) *DataShareSessionUpdate {
	_u.mutation.SetPayloadEncoding(v)
	return _u
}

// SetNillablePayloadEncoding sets the "payload_encoding" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillablePayloadEncoding(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetPayloadEncoding(*v)
	}
	return _u
}

// SetPayloadBytes sets the "payload_bytes" field.
func (_u *DataShareSessionUpdate) SetPayloadBytes(v int64) *DataShareSessionUpdate {
	_u.mutation.ResetPayloadBytes()
	_u.mutation.SetPayloadBytes(v)
	return _u
}

// SetNillablePayloadBytes sets the "payload_bytes" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillablePayloadBytes(v *int64) *DataShareSessionUpdate {
	if v != nil {
		_u.SetPayloadBytes(*v)
	}
	return _u
}

// AddPayloadBytes adds value to the "payload_bytes" field.
func (_u *DataShareSessionUpdate) AddPayloadBytes(v int64) *DataShareSessionUpdate {
	_u.mutation.AddPayloadBytes(v)
	return _u
}

// SetExportable sets the "exportable" field.
func (_u *DataShareSessionUpdate) SetExportable(v bool) *DataShareSessionUpdate {
	_u.mutation.SetExportable(v)
	return _u
}

// SetNillableExportable sets the "exportable" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableExportable(v *bool) *DataShareSessionUpdate {
	if v != nil {
		_u.SetExportable(*v)
	}
	return _u
}

// SetQualityStatus sets the "quality_status" field.
func (_u *DataShareSessionUpdate) SetQualityStatus(v string) *DataShareSessionUpdate {
	_u.mutation.SetQualityStatus(v)
	return _u
}

// SetNillableQualityStatus sets the "quality_status" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableQualityStatus(v *string) *DataShareSessionUpdate {
	if v != nil {
		_u.SetQualityStatus(*v)
	}
	return _u
}

// SetQualityErrors sets the "quality_errors" field.
func (_u *DataShareSessionUpdate) SetQualityErrors(v []string) *DataShareSessionUpdate {
	_u.mutation.SetQualityErrors(v)
	return _u
}

// AppendQualityErrors appends value to the "quality_errors" field.
func (_u *DataShareSessionUpdate) AppendQualityErrors(v []string) *DataShareSessionUpdate {
	_u.mutation.AppendQualityErrors(v)
	return _u
}

// ClearQualityErrors clears the value of the "quality_errors" field.
func (_u *DataShareSessionUpdate) ClearQualityErrors() *DataShareSessionUpdate {
	_u.mutation.ClearQualityErrors()
	return _u
}

// SetStorageBytes sets the "storage_bytes" field.
func (_u *DataShareSessionUpdate) SetStorageBytes(v int64) *DataShareSessionUpdate {
	_u.mutation.ResetStorageBytes()
	_u.mutation.SetStorageBytes(v)
	return _u
}

// SetNillableStorageBytes sets the "storage_bytes" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableStorageBytes(v *int64) *DataShareSessionUpdate {
	if v != nil {
		_u.SetStorageBytes(*v)
	}
	return _u
}

// AddStorageBytes adds value to the "storage_bytes" field.
func (_u *DataShareSessionUpdate) AddStorageBytes(v int64) *DataShareSessionUpdate {
	_u.mutation.AddStorageBytes(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *DataShareSessionUpdate) SetInputTokens(v int64) *DataShareSessionUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableInputTokens(v *int64) *DataShareSessionUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *DataShareSessionUpdate) AddInputTokens(v int64) *DataShareSessionUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *DataShareSessionUpdate) SetOutputTokens(v int64) *DataShareSessionUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableOutputTokens(v *int64) *DataShareSessionUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *DataShareSessionUpdate) AddOutputTokens(v int64) *DataShareSessionUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *DataShareSessionUpdate) SetTotalTokens(v int64) *DataShareSessionUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableTotalTokens(v *int64) *DataShareSessionUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *DataShareSessionUpdate) AddTotalTokens(v int64) *DataShareSessionUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *DataShareSessionUpdate) SetActualCost(v float64) *DataShareSessionUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableActualCost(v *float64) *DataShareSessionUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *DataShareSessionUpdate) AddActualCost(v float64) *DataShareSessionUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *DataShareSessionUpdate) ClearActualCost() *DataShareSessionUpdate {
	_u.mutation.ClearActualCost()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DataShareSessionUpdate) SetUserID(v int64) *DataShareSessionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableUserID(v *int64) *DataShareSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DataShareSessionUpdate) AddUserID(v int64) *DataShareSessionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *DataShareSessionUpdate) SetAPIKeyID(v int64) *DataShareSessionUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableAPIKeyID(v *int64) *DataShareSessionUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *DataShareSessionUpdate) AddAPIKeyID(v int64) *DataShareSessionUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DataShareSessionUpdate) SetGroupID(v int64) *DataShareSessionUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableGroupID(v *int64) *DataShareSessionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *DataShareSessionUpdate) AddGroupID(v int64) *DataShareSessionUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *DataShareSessionUpdate) SetEndedAt(v time.Time) *DataShareSessionUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *DataShareSessionUpdate) SetNillableEndedAt(v *time.Time) *DataShareSessionUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *DataShareSessionUpdate) ClearEndedAt() *DataShareSessionUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DataShareSessionUpdate) SetUpdatedAt(v time.Time) *DataShareSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DataShareSessionMutation object of the builder.
func (_u *DataShareSessionUpdate) Mutation() *DataShareSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DataShareSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DataShareSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DataShareSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DataShareSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DataShareSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := datasharesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DataShareSessionUpdate) check() error {
	if v, ok := _u.mutation.TrajectoryID(); ok {
		if err := datasharesession.TrajectoryIDValidator(v); err != nil {
			return &ValidationError{Name: "trajectory_id", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.trajectory_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := datasharesession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Dataset(); ok {
		if err := datasharesession.DatasetValidator(v); err != nil {
			return &ValidationError{Name: "dataset", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.dataset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := datasharesession.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := datasharesession.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPath(); ok {
		if err := datasharesession.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.request_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := datasharesession.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := datasharesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadEncoding(); ok {
		if err := datasharesession.PayloadEncodingValidator(v); err != nil {
			return &ValidationError{Name: "payload_encoding", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.payload_encoding": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualityStatus(); ok {
		if err := datasharesession.QualityStatusValidator(v); err != nil {
			return &ValidationError{Name: "quality_status", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.quality_status": %w`, err)}
		}
	}
	return nil
}

func (_u *DataShareSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(datasharesession.Table, datasharesession.Columns, sqlgraph.NewFieldSpec(datasharesession.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrajectoryID(); ok {
		_spec.SetField(datasharesession.FieldTrajectoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(datasharesession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Dataset(); ok {
		_spec.SetField(datasharesession.FieldDataset, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(datasharesession.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(datasharesession.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(datasharesession.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(datasharesession.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(datasharesession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsFinalSnapshot(); ok {
		_spec.SetField(datasharesession.FieldIsFinalSnapshot, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SourceRequestCount(); ok {
		_spec.SetField(datasharesession.FieldSourceRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceRequestCount(); ok {
		_spec.AddField(datasharesession.FieldSourceRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(datasharesession.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(datasharesession.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Tools(); ok {
		_spec.SetField(datasharesession.FieldTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, datasharesession.FieldTools, value)
		})
	}
	if _u.mutation.ToolsCleared() {
		_spec.ClearField(datasharesession.FieldTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.Messages(); ok {
		_spec.SetField(datasharesession.FieldMessages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, datasharesession.FieldMessages, value)
		})
	}
	if _u.mutation.MessagesCleared() {
		_spec.ClearField(datasharesession.FieldMessages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Usage(); ok {
		_spec.SetField(datasharesession.FieldUsage, field.TypeJSON, value)
	}
	if _u.mutation.UsageCleared() {
		_spec.ClearField(datasharesession.FieldUsage, field.TypeJSON)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(datasharesession.FieldMeta, field.TypeJSON, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(datasharesession.FieldMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.SessionJSON(); ok {
		_spec.SetField(datasharesession.FieldSessionJSON, field.TypeJSON, value)
	}
	if _u.mutation.SessionJSONCleared() {
		_spec.ClearField(datasharesession.FieldSessionJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.PayloadCompressed(); ok {
		_spec.SetField(datasharesession.FieldPayloadCompressed, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCompressedCleared() {
		_spec.ClearField(datasharesession.FieldPayloadCompressed, field.TypeBytes)
	}
	if value, ok := _u.mutation.PayloadEncoding(); ok {
		_spec.SetField(datasharesession.FieldPayloadEncoding, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadBytes(); ok {
		_spec.SetField(datasharesession.FieldPayloadBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayloadBytes(); ok {
		_spec.AddField(datasharesession.FieldPayloadBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Exportable(); ok {
		_spec.SetField(datasharesession.FieldExportable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QualityStatus(); ok {
		_spec.SetField(datasharesession.FieldQualityStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.QualityErrors(); ok {
		_spec.SetField(datasharesession.FieldQualityErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedQualityErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, datasharesession.FieldQualityErrors, value)
		})
	}
	if _u.mutation.QualityErrorsCleared() {
		_spec.ClearField(datasharesession.FieldQualityErrors, field.TypeJSON)
	}
	if value, ok := _u.mutation.StorageBytes(); ok {
		_spec.SetField(datasharesession.FieldStorageBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStorageBytes(); ok {
		_spec.AddField(datasharesession.FieldStorageBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(datasharesession.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(datasharesession.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(datasharesession.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(datasharesession.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(datasharesession.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(datasharesession.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(datasharesession.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(datasharesession.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(datasharesession.FieldActualCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(datasharesession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(datasharesession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(datasharesession.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(datasharesession.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(datasharesession.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(datasharesession.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(datasharesession.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(datasharesession.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(datasharesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{datasharesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DataShareSessionUpdateOne is the builder for updating a single DataShareSession entity.
type DataShareSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DataShareSessionMutation
}

// SetTrajectoryID sets the "trajectory_id" field.
func (_u *DataShareSessionUpdateOne) SetTrajectoryID(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetTrajectoryID(v)
	return _u
}

// SetNillableTrajectoryID sets the "trajectory_id" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableTrajectoryID(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetTrajectoryID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *DataShareSessionUpdateOne) SetSessionID(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableSessionID(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetDataset sets the "dataset" field.
func (_u *DataShareSessionUpdateOne) SetDataset(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetDataset(v)
	return _u
}

// SetNillableDataset sets the "dataset" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableDataset(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetDataset(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *DataShareSessionUpdateOne) SetProvider(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableProvider(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *DataShareSessionUpdateOne) SetModel(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableModel(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestPath sets the "request_path" field.
func (_u *DataShareSessionUpdateOne) SetRequestPath(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetRequestPath(v)
	return _u
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableRequestPath(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetRequestPath(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *DataShareSessionUpdateOne) SetUserAgent(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableUserAgent(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DataShareSessionUpdateOne) SetStatus(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableStatus(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsFinalSnapshot sets the "is_final_snapshot" field.
func (_u *DataShareSessionUpdateOne) SetIsFinalSnapshot(v bool) *DataShareSessionUpdateOne {
	_u.mutation.SetIsFinalSnapshot(v)
	return _u
}

// SetNillableIsFinalSnapshot sets the "is_final_snapshot" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableIsFinalSnapshot(v *bool) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetIsFinalSnapshot(*v)
	}
	return _u
}

// SetSourceRequestCount sets the "source_request_count" field.
func (_u *DataShareSessionUpdateOne) SetSourceRequestCount(v int) *DataShareSessionUpdateOne {
	_u.mutation.ResetSourceRequestCount()
	_u.mutation.SetSourceRequestCount(v)
	return _u
}

// SetNillableSourceRequestCount sets the "source_request_count" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableSourceRequestCount(v *int) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetSourceRequestCount(*v)
	}
	return _u
}

// AddSourceRequestCount adds value to the "source_request_count" field.
func (_u *DataShareSessionUpdateOne) AddSourceRequestCount(v int) *DataShareSessionUpdateOne {
	_u.mutation.AddSourceRequestCount(v)
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *DataShareSessionUpdateOne) SetSystemPrompt(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableSystemPrompt(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *DataShareSessionUpdateOne) ClearSystemPrompt() *DataShareSessionUpdateOne {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetTools sets the "tools" field.
func (_u *DataShareSessionUpdateOne) SetTools(v []map[string]interface{}) *DataShareSessionUpdateOne {
	_u.mutation.SetTools(v)
	return _u
}

// AppendTools appends value to the "tools" field.
func (_u *DataShareSessionUpdateOne) AppendTools(v []map[string]interface{}) *DataShareSessionUpdateOne {
	_u.mutation.AppendTools(v)
	return _u
}

// ClearTools clears the value of the "tools" field.
func (_u *DataShareSessionUpdateOne) ClearTools() *DataShareSessionUpdateOne {
	_u.mutation.ClearTools()
	return _u
}

// SetMessages sets the "messages" field.
func (_u *DataShareSessionUpdateOne) SetMessages(v []map[string]interface{}) *DataShareSessionUpdateOne {
	_u.mutation.SetMessages(v)
	return _u
}

// AppendMessages appends value to the "messages" field.
func (_u *DataShareSessionUpdateOne) AppendMessages(v []map[string]interface{}) *DataShareSessionUpdateOne {
	_u.mutation.AppendMessages(v)
	return _u
}

// ClearMessages clears the value of the "messages" field.
func (_u *DataShareSessionUpdateOne) ClearMessages() *DataShareSessionUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// SetUsage sets the "usage" field.
func (_u *DataShareSessionUpdateOne) SetUsage(v map[string]interface{}) *DataShareSessionUpdateOne {
	_u.mutation.SetUsage(v)
	return _u
}

// ClearUsage clears the value of the "usage" field.
func (_u *DataShareSessionUpdateOne) ClearUsage() *DataShareSessionUpdateOne {
	_u.mutation.ClearUsage()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *DataShareSessionUpdateOne) SetMeta(v map[string]interface{}) *DataShareSessionUpdateOne {
	_u.mutation.SetMeta(v)
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *DataShareSessionUpdateOne) ClearMeta() *DataShareSessionUpdateOne {
	_u.mutation.ClearMeta()
	return _u
}

// SetSessionJSON sets the "session_json" field.
func (_u *DataShareSessionUpdateOne) SetSessionJSON(v map[string]interface{}) *DataShareSessionUpdateOne {
	_u.mutation.SetSessionJSON(v)
	return _u
}

// ClearSessionJSON clears the value of the "session_json" field.
func (_u *DataShareSessionUpdateOne) ClearSessionJSON() *DataShareSessionUpdateOne {
	_u.mutation.ClearSessionJSON()
	return _u
}

// SetPayloadCompressed sets the "payload_compressed" field.
func (_u *DataShareSessionUpdateOne) SetPayloadCompressed(v []byte) *DataShareSessionUpdateOne {
	_u.mutation.SetPayloadCompressed(v)
	return _u
}

// ClearPayloadCompressed clears the value of the "payload_compressed" field.
func (_u *DataShareSessionUpdateOne) ClearPayloadCompressed() *DataShareSessionUpdateOne {
	_u.mutation.ClearPayloadCompressed()
	return _u
}

// SetPayloadEncoding sets the "payload_encoding" field.
func (_u *DataShareSessionUpdateOne) SetPayloadEncoding(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetPayloadEncoding(v)
	return _u
}

// SetNillablePayloadEncoding sets the "payload_encoding" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillablePayloadEncoding(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetPayloadEncoding(*v)
	}
	return _u
}

// SetPayloadBytes sets the "payload_bytes" field.
func (_u *DataShareSessionUpdateOne) SetPayloadBytes(v int64) *DataShareSessionUpdateOne {
	_u.mutation.ResetPayloadBytes()
	_u.mutation.SetPayloadBytes(v)
	return _u
}

// SetNillablePayloadBytes sets the "payload_bytes" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillablePayloadBytes(v *int64) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetPayloadBytes(*v)
	}
	return _u
}

// AddPayloadBytes adds value to the "payload_bytes" field.
func (_u *DataShareSessionUpdateOne) AddPayloadBytes(v int64) *DataShareSessionUpdateOne {
	_u.mutation.AddPayloadBytes(v)
	return _u
}

// SetExportable sets the "exportable" field.
func (_u *DataShareSessionUpdateOne) SetExportable(v bool) *DataShareSessionUpdateOne {
	_u.mutation.SetExportable(v)
	return _u
}

// SetNillableExportable sets the "exportable" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableExportable(v *bool) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetExportable(*v)
	}
	return _u
}

// SetQualityStatus sets the "quality_status" field.
func (_u *DataShareSessionUpdateOne) SetQualityStatus(v string) *DataShareSessionUpdateOne {
	_u.mutation.SetQualityStatus(v)
	return _u
}

// SetNillableQualityStatus sets the "quality_status" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableQualityStatus(v *string) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetQualityStatus(*v)
	}
	return _u
}

// SetQualityErrors sets the "quality_errors" field.
func (_u *DataShareSessionUpdateOne) SetQualityErrors(v []string) *DataShareSessionUpdateOne {
	_u.mutation.SetQualityErrors(v)
	return _u
}

// AppendQualityErrors appends value to the "quality_errors" field.
func (_u *DataShareSessionUpdateOne) AppendQualityErrors(v []string) *DataShareSessionUpdateOne {
	_u.mutation.AppendQualityErrors(v)
	return _u
}

// ClearQualityErrors clears the value of the "quality_errors" field.
func (_u *DataShareSessionUpdateOne) ClearQualityErrors() *DataShareSessionUpdateOne {
	_u.mutation.ClearQualityErrors()
	return _u
}

// SetStorageBytes sets the "storage_bytes" field.
func (_u *DataShareSessionUpdateOne) SetStorageBytes(v int64) *DataShareSessionUpdateOne {
	_u.mutation.ResetStorageBytes()
	_u.mutation.SetStorageBytes(v)
	return _u
}

// SetNillableStorageBytes sets the "storage_bytes" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableStorageBytes(v *int64) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetStorageBytes(*v)
	}
	return _u
}

// AddStorageBytes adds value to the "storage_bytes" field.
func (_u *DataShareSessionUpdateOne) AddStorageBytes(v int64) *DataShareSessionUpdateOne {
	_u.mutation.AddStorageBytes(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *DataShareSessionUpdateOne) SetInputTokens(v int64) *DataShareSessionUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableInputTokens(v *int64) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *DataShareSessionUpdateOne) AddInputTokens(v int64) *DataShareSessionUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *DataShareSessionUpdateOne) SetOutputTokens(v int64) *DataShareSessionUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableOutputTokens(v *int64) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *DataShareSessionUpdateOne) AddOutputTokens(v int64) *DataShareSessionUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *DataShareSessionUpdateOne) SetTotalTokens(v int64) *DataShareSessionUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableTotalTokens(v *int64) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *DataShareSessionUpdateOne) AddTotalTokens(v int64) *DataShareSessionUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *DataShareSessionUpdateOne) SetActualCost(v float64) *DataShareSessionUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableActualCost(v *float64) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *DataShareSessionUpdateOne) AddActualCost(v float64) *DataShareSessionUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *DataShareSessionUpdateOne) ClearActualCost() *DataShareSessionUpdateOne {
	_u.mutation.ClearActualCost()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DataShareSessionUpdateOne) SetUserID(v int64) *DataShareSessionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableUserID(v *int64) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DataShareSessionUpdateOne) AddUserID(v int64) *DataShareSessionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *DataShareSessionUpdateOne) SetAPIKeyID(v int64) *DataShareSessionUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableAPIKeyID(v *int64) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *DataShareSessionUpdateOne) AddAPIKeyID(v int64) *DataShareSessionUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DataShareSessionUpdateOne) SetGroupID(v int64) *DataShareSessionUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableGroupID(v *int64) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *DataShareSessionUpdateOne) AddGroupID(v int64) *DataShareSessionUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *DataShareSessionUpdateOne) SetEndedAt(v time.Time) *DataShareSessionUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *DataShareSessionUpdateOne) SetNillableEndedAt(v *time.Time) *DataShareSessionUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *DataShareSessionUpdateOne) ClearEndedAt() *DataShareSessionUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DataShareSessionUpdateOne) SetUpdatedAt(v time.Time) *DataShareSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DataShareSessionMutation object of the builder.
func (_u *DataShareSessionUpdateOne) Mutation() *DataShareSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the DataShareSessionUpdate builder.
func (_u *DataShareSessionUpdateOne) Where(ps ...predicate.DataShareSession) *DataShareSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DataShareSessionUpdateOne) Select(field string, fields ...string) *DataShareSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DataShareSession entity.
func (_u *DataShareSessionUpdateOne) Save(ctx context.Context) (*DataShareSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DataShareSessionUpdateOne) SaveX(ctx context.Context) *DataShareSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DataShareSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DataShareSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DataShareSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := datasharesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DataShareSessionUpdateOne) check() error {
	if v, ok := _u.mutation.TrajectoryID(); ok {
		if err := datasharesession.TrajectoryIDValidator(v); err != nil {
			return &ValidationError{Name: "trajectory_id", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.trajectory_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := datasharesession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Dataset(); ok {
		if err := datasharesession.DatasetValidator(v); err != nil {
			return &ValidationError{Name: "dataset", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.dataset": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := datasharesession.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := datasharesession.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPath(); ok {
		if err := datasharesession.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.request_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := datasharesession.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := datasharesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadEncoding(); ok {
		if err := datasharesession.PayloadEncodingValidator(v); err != nil {
			return &ValidationError{Name: "payload_encoding", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.payload_encoding": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QualityStatus(); ok {
		if err := datasharesession.QualityStatusValidator(v); err != nil {
			return &ValidationError{Name: "quality_status", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.quality_status": %w`, err)}
		}
	}
	return nil
}

func (_u *DataShareSessionUpdateOne) sqlSave(ctx context.Context) (_node *DataShareSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(datasharesession.Table, datasharesession.Columns, sqlgraph.NewFieldSpec(datasharesession.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DataShareSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, datasharesession.FieldID)
		for _, f := range fields {
			if !datasharesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != datasharesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrajectoryID(); ok {
		_spec.SetField(datasharesession.FieldTrajectoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(datasharesession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Dataset(); ok {
		_spec.SetField(datasharesession.FieldDataset, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(datasharesession.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(datasharesession.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestPath(); ok {
		_spec.SetField(datasharesession.FieldRequestPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(datasharesession.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(datasharesession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsFinalSnapshot(); ok {
		_spec.SetField(datasharesession.FieldIsFinalSnapshot, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SourceRequestCount(); ok {
		_spec.SetField(datasharesession.FieldSourceRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceRequestCount(); ok {
		_spec.AddField(datasharesession.FieldSourceRequestCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(datasharesession.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(datasharesession.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Tools(); ok {
		_spec.SetField(datasharesession.FieldTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, datasharesession.FieldTools, value)
		})
	}
	if _u.mutation.ToolsCleared() {
		_spec.ClearField(datasharesession.FieldTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.Messages(); ok {
		_spec.SetField(datasharesession.FieldMessages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, datasharesession.FieldMessages, value)
		})
	}
	if _u.mutation.MessagesCleared() {
		_spec.ClearField(datasharesession.FieldMessages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Usage(); ok {
		_spec.SetField(datasharesession.FieldUsage, field.TypeJSON, value)
	}
	if _u.mutation.UsageCleared() {
		_spec.ClearField(datasharesession.FieldUsage, field.TypeJSON)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(datasharesession.FieldMeta, field.TypeJSON, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(datasharesession.FieldMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.SessionJSON(); ok {
		_spec.SetField(datasharesession.FieldSessionJSON, field.TypeJSON, value)
	}
	if _u.mutation.SessionJSONCleared() {
		_spec.ClearField(datasharesession.FieldSessionJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.PayloadCompressed(); ok {
		_spec.SetField(datasharesession.FieldPayloadCompressed, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCompressedCleared() {
		_spec.ClearField(datasharesession.FieldPayloadCompressed, field.TypeBytes)
	}
	if value, ok := _u.mutation.PayloadEncoding(); ok {
		_spec.SetField(datasharesession.FieldPayloadEncoding, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadBytes(); ok {
		_spec.SetField(datasharesession.FieldPayloadBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayloadBytes(); ok {
		_spec.AddField(datasharesession.FieldPayloadBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Exportable(); ok {
		_spec.SetField(datasharesession.FieldExportable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QualityStatus(); ok {
		_spec.SetField(datasharesession.FieldQualityStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.QualityErrors(); ok {
		_spec.SetField(datasharesession.FieldQualityErrors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedQualityErrors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, datasharesession.FieldQualityErrors, value)
		})
	}
	if _u.mutation.QualityErrorsCleared() {
		_spec.ClearField(datasharesession.FieldQualityErrors, field.TypeJSON)
	}
	if value, ok := _u.mutation.StorageBytes(); ok {
		_spec.SetField(datasharesession.FieldStorageBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStorageBytes(); ok {
		_spec.AddField(datasharesession.FieldStorageBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(datasharesession.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(datasharesession.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(datasharesession.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(datasharesession.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(datasharesession.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(datasharesession.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(datasharesession.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(datasharesession.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(datasharesession.FieldActualCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(datasharesession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(datasharesession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(datasharesession.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(datasharesession.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(datasharesession.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(datasharesession.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(datasharesession.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(datasharesession.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(datasharesession.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DataShareSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{datasharesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
