// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/BrandonVee/TokenRouter/ent/datasharesession"
)

// DataShareSession is the model entity for the DataShareSession schema.
type DataShareSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TrajectoryID holds the value of the "trajectory_id" field.
	TrajectoryID string `json:"trajectory_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// Dataset holds the value of the "dataset" field.
	Dataset string `json:"dataset,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// RequestPath holds the value of the "request_path" field.
	RequestPath string `json:"request_path,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// IsFinalSnapshot holds the value of the "is_final_snapshot" field.
	IsFinalSnapshot bool `json:"is_final_snapshot,omitempty"`
	// SourceRequestCount holds the value of the "source_request_count" field.
	SourceRequestCount int `json:"source_request_count,omitempty"`
	// SystemPrompt holds the value of the "system_prompt" field.
	SystemPrompt *string `json:"system_prompt,omitempty"`
	// Tools holds the value of the "tools" field.
	Tools []map[string]interface{} `json:"tools,omitempty"`
	// Messages holds the value of the "messages" field.
	Messages []map[string]interface{} `json:"messages,omitempty"`
	// Usage holds the value of the "usage" field.
	Usage map[string]interface{} `json:"usage,omitempty"`
	// Meta holds the value of the "meta" field.
	Meta map[string]interface{} `json:"meta,omitempty"`
	// SessionJSON holds the value of the "session_json" field.
	SessionJSON map[string]interface{} `json:"session_json,omitempty"`
	// PayloadCompressed holds the value of the "payload_compressed" field.
	PayloadCompressed *[]byte `json:"payload_compressed,omitempty"`
	// PayloadEncoding holds the value of the "payload_encoding" field.
	PayloadEncoding string `json:"payload_encoding,omitempty"`
	// PayloadBytes holds the value of the "payload_bytes" field.
	PayloadBytes int64 `json:"payload_bytes,omitempty"`
	// Exportable holds the value of the "exportable" field.
	Exportable bool `json:"exportable,omitempty"`
	// QualityStatus holds the value of the "quality_status" field.
	QualityStatus string `json:"quality_status,omitempty"`
	// QualityErrors holds the value of the "quality_errors" field.
	QualityErrors []string `json:"quality_errors,omitempty"`
	// StorageBytes holds the value of the "storage_bytes" field.
	StorageBytes int64 `json:"storage_bytes,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// TotalTokens holds the value of the "total_tokens" field.
	TotalTokens int64 `json:"total_tokens,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost *float64 `json:"actual_cost,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DataShareSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case datasharesession.FieldTools, datasharesession.FieldMessages, datasharesession.FieldUsage, datasharesession.FieldMeta, datasharesession.FieldSessionJSON, datasharesession.FieldPayloadCompressed, datasharesession.FieldQualityErrors:
			values[i] = new([]byte)
		case datasharesession.FieldIsFinalSnapshot, datasharesession.FieldExportable:
			values[i] = new(sql.NullBool)
		case datasharesession.FieldActualCost:
			values[i] = new(sql.NullFloat64)
		case datasharesession.FieldID, datasharesession.FieldSourceRequestCount, datasharesession.FieldPayloadBytes, datasharesession.FieldStorageBytes, datasharesession.FieldInputTokens, datasharesession.FieldOutputTokens, datasharesession.FieldTotalTokens, datasharesession.FieldUserID, datasharesession.FieldAPIKeyID, datasharesession.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case datasharesession.FieldTrajectoryID, datasharesession.FieldSessionID, datasharesession.FieldDataset, datasharesession.FieldProvider, datasharesession.FieldModel, datasharesession.FieldRequestPath, datasharesession.FieldUserAgent, datasharesession.FieldStatus, datasharesession.FieldSystemPrompt, datasharesession.FieldPayloadEncoding, datasharesession.FieldQualityStatus:
			values[i] = new(sql.NullString)
		case datasharesession.FieldCreatedAt, datasharesession.FieldEndedAt, datasharesession.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DataShareSession fields.
func (_m *DataShareSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case datasharesession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case datasharesession.FieldTrajectoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trajectory_id", values[i])
			} else if value.Valid {
				_m.TrajectoryID = value.String
			}
		case datasharesession.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case datasharesession.FieldDataset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dataset", values[i])
			} else if value.Valid {
				_m.Dataset = value.String
			}
		case datasharesession.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case datasharesession.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case datasharesession.FieldRequestPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_path", values[i])
			} else if value.Valid {
				_m.RequestPath = value.String
			}
		case datasharesession.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case datasharesession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case datasharesession.FieldIsFinalSnapshot:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_final_snapshot", values[i])
			} else if value.Valid {
				_m.IsFinalSnapshot = value.Bool
			}
		case datasharesession.FieldSourceRequestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_request_count", values[i])
			} else if value.Valid {
				_m.SourceRequestCount = int(value.Int64)
			}
		case datasharesession.FieldSystemPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system_prompt", values[i])
			} else if value.Valid {
				_m.SystemPrompt = new(string)
				*_m.SystemPrompt = value.String
			}
		case datasharesession.FieldTools:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tools", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tools); err != nil {
					return fmt.Errorf("unmarshal field tools: %w", err)
				}
			}
		case datasharesession.FieldMessages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field messages", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Messages); err != nil {
					return fmt.Errorf("unmarshal field messages: %w", err)
				}
			}
		case datasharesession.FieldUsage:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field usage", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Usage); err != nil {
					return fmt.Errorf("unmarshal field usage: %w", err)
				}
			}
		case datasharesession.FieldMeta:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field meta", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Meta); err != nil {
					return fmt.Errorf("unmarshal field meta: %w", err)
				}
			}
		case datasharesession.FieldSessionJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field session_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SessionJSON); err != nil {
					return fmt.Errorf("unmarshal field session_json: %w", err)
				}
			}
		case datasharesession.FieldPayloadCompressed:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload_compressed", values[i])
			} else if value != nil {
				_m.PayloadCompressed = value
			}
		case datasharesession.FieldPayloadEncoding:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_encoding", values[i])
			} else if value.Valid {
				_m.PayloadEncoding = value.String
			}
		case datasharesession.FieldPayloadBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payload_bytes", values[i])
			} else if value.Valid {
				_m.PayloadBytes = value.Int64
			}
		case datasharesession.FieldExportable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field exportable", values[i])
			} else if value.Valid {
				_m.Exportable = value.Bool
			}
		case datasharesession.FieldQualityStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality_status", values[i])
			} else if value.Valid {
				_m.QualityStatus = value.String
			}
		case datasharesession.FieldQualityErrors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field quality_errors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.QualityErrors); err != nil {
					return fmt.Errorf("unmarshal field quality_errors: %w", err)
				}
			}
		case datasharesession.FieldStorageBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field storage_bytes", values[i])
			} else if value.Valid {
				_m.StorageBytes = value.Int64
			}
		case datasharesession.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case datasharesession.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case datasharesession.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = value.Int64
			}
		case datasharesession.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = new(float64)
				*_m.ActualCost = value.Float64
			}
		case datasharesession.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case datasharesession.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case datasharesession.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case datasharesession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case datasharesession.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		case datasharesession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DataShareSession.
// This includes values selected through modifiers, order, etc.
func (_m *DataShareSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DataShareSession.
// Note that you need to call DataShareSession.Unwrap() before calling this method if this DataShareSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DataShareSession) Update() *DataShareSessionUpdateOne {
	return NewDataShareSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DataShareSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DataShareSession) Unwrap() *DataShareSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DataShareSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DataShareSession) String() string {
	var builder strings.Builder
	builder.WriteString("DataShareSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("trajectory_id=")
	builder.WriteString(_m.TrajectoryID)
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("dataset=")
	builder.WriteString(_m.Dataset)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("request_path=")
	builder.WriteString(_m.RequestPath)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("is_final_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsFinalSnapshot))
	builder.WriteString(", ")
	builder.WriteString("source_request_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceRequestCount))
	builder.WriteString(", ")
	if v := _m.SystemPrompt; v != nil {
		builder.WriteString("system_prompt=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("tools=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tools))
	builder.WriteString(", ")
	builder.WriteString("messages=")
	builder.WriteString(fmt.Sprintf("%v", _m.Messages))
	builder.WriteString(", ")
	builder.WriteString("usage=")
	builder.WriteString(fmt.Sprintf("%v", _m.Usage))
	builder.WriteString(", ")
	builder.WriteString("meta=")
	builder.WriteString(fmt.Sprintf("%v", _m.Meta))
	builder.WriteString(", ")
	builder.WriteString("session_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionJSON))
	builder.WriteString(", ")
	if v := _m.PayloadCompressed; v != nil {
		builder.WriteString("payload_compressed=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("payload_encoding=")
	builder.WriteString(_m.PayloadEncoding)
	builder.WriteString(", ")
	builder.WriteString("payload_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayloadBytes))
	builder.WriteString(", ")
	builder.WriteString("exportable=")
	builder.WriteString(fmt.Sprintf("%v", _m.Exportable))
	builder.WriteString(", ")
	builder.WriteString("quality_status=")
	builder.WriteString(_m.QualityStatus)
	builder.WriteString(", ")
	builder.WriteString("quality_errors=")
	builder.WriteString(fmt.Sprintf("%v", _m.QualityErrors))
	builder.WriteString(", ")
	builder.WriteString("storage_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.StorageBytes))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokens))
	builder.WriteString(", ")
	if v := _m.ActualCost; v != nil {
		builder.WriteString("actual_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DataShareSessions is a parsable slice of DataShareSession.
type DataShareSessions []*DataShareSession
