// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BrandonVee/TokenRouter/ent/datasharesession"
)

// DataShareSessionCreate is the builder for creating a DataShareSession entity.
type DataShareSessionCreate struct {
	config
	mutation *DataShareSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTrajectoryID sets the "trajectory_id" field.
func (_c *DataShareSessionCreate) SetTrajectoryID(v string) *DataShareSessionCreate {
	_c.mutation.SetTrajectoryID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *DataShareSessionCreate) SetSessionID(v string) *DataShareSessionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetDataset sets the "dataset" field.
func (_c *DataShareSessionCreate) SetDataset(v string) *DataShareSessionCreate {
	_c.mutation.SetDataset(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *DataShareSessionCreate) SetProvider(v string) *DataShareSessionCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *DataShareSessionCreate) SetModel(v string) *DataShareSessionCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetRequestPath sets the "request_path" field.
func (_c *DataShareSessionCreate) SetRequestPath(v string) *DataShareSessionCreate {
	_c.mutation.SetRequestPath(v)
	return _c
}

// SetNillableRequestPath sets the "request_path" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableRequestPath(v *string) *DataShareSessionCreate {
	if v != nil {
		_c.SetRequestPath(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *DataShareSessionCreate) SetUserAgent(v string) *DataShareSessionCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableUserAgent(v *string) *DataShareSessionCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DataShareSessionCreate) SetStatus(v string) *DataShareSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableStatus(v *string) *DataShareSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIsFinalSnapshot sets the "is_final_snapshot" field.
func (_c *DataShareSessionCreate) SetIsFinalSnapshot(v bool) *DataShareSessionCreate {
	_c.mutation.SetIsFinalSnapshot(v)
	return _c
}

// SetNillableIsFinalSnapshot sets the "is_final_snapshot" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableIsFinalSnapshot(v *bool) *DataShareSessionCreate {
	if v != nil {
		_c.SetIsFinalSnapshot(*v)
	}
	return _c
}

// SetSourceRequestCount sets the "source_request_count" field.
func (_c *DataShareSessionCreate) SetSourceRequestCount(v int) *DataShareSessionCreate {
	_c.mutation.SetSourceRequestCount(v)
	return _c
}

// SetNillableSourceRequestCount sets the "source_request_count" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableSourceRequestCount(v *int) *DataShareSessionCreate {
	if v != nil {
		_c.SetSourceRequestCount(*v)
	}
	return _c
}

// SetSystemPrompt sets the "system_prompt" field.
func (_c *DataShareSessionCreate) SetSystemPrompt(v string) *DataShareSessionCreate {
	_c.mutation.SetSystemPrompt(v)
	return _c
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableSystemPrompt(v *string) *DataShareSessionCreate {
	if v != nil {
		_c.SetSystemPrompt(*v)
	}
	return _c
}

// SetTools sets the "tools" field.
func (_c *DataShareSessionCreate) SetTools(v []map[string]interface{}) *DataShareSessionCreate {
	_c.mutation.SetTools(v)
	return _c
}

// SetMessages sets the "messages" field.
func (_c *DataShareSessionCreate) SetMessages(v []map[string]interface{}) *DataShareSessionCreate {
	_c.mutation.SetMessages(v)
	return _c
}

// SetUsage sets the "usage" field.
func (_c *DataShareSessionCreate) SetUsage(v map[string]interface{}) *DataShareSessionCreate {
	_c.mutation.SetUsage(v)
	return _c
}

// SetMeta sets the "meta" field.
func (_c *DataShareSessionCreate) SetMeta(v map[string]interface{}) *DataShareSessionCreate {
	_c.mutation.SetMeta(v)
	return _c
}

// SetSessionJSON sets the "session_json" field.
func (_c *DataShareSessionCreate) SetSessionJSON(v map[string]interface{}) *DataShareSessionCreate {
	_c.mutation.SetSessionJSON(v)
	return _c
}

// SetPayloadCompressed sets the "payload_compressed" field.
func (_c *DataShareSessionCreate) SetPayloadCompressed(v []byte) *DataShareSessionCreate {
	_c.mutation.SetPayloadCompressed(v)
	return _c
}

// SetPayloadEncoding sets the "payload_encoding" field.
func (_c *DataShareSessionCreate) SetPayloadEncoding(v string) *DataShareSessionCreate {
	_c.mutation.SetPayloadEncoding(v)
	return _c
}

// SetNillablePayloadEncoding sets the "payload_encoding" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillablePayloadEncoding(v *string) *DataShareSessionCreate {
	if v != nil {
		_c.SetPayloadEncoding(*v)
	}
	return _c
}

// SetPayloadBytes sets the "payload_bytes" field.
func (_c *DataShareSessionCreate) SetPayloadBytes(v int64) *DataShareSessionCreate {
	_c.mutation.SetPayloadBytes(v)
	return _c
}

// SetNillablePayloadBytes sets the "payload_bytes" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillablePayloadBytes(v *int64) *DataShareSessionCreate {
	if v != nil {
		_c.SetPayloadBytes(*v)
	}
	return _c
}

// SetExportable sets the "exportable" field.
func (_c *DataShareSessionCreate) SetExportable(v bool) *DataShareSessionCreate {
	_c.mutation.SetExportable(v)
	return _c
}

// SetNillableExportable sets the "exportable" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableExportable(v *bool) *DataShareSessionCreate {
	if v != nil {
		_c.SetExportable(*v)
	}
	return _c
}

// SetQualityStatus sets the "quality_status" field.
func (_c *DataShareSessionCreate) SetQualityStatus(v string) *DataShareSessionCreate {
	_c.mutation.SetQualityStatus(v)
	return _c
}

// SetNillableQualityStatus sets the "quality_status" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableQualityStatus(v *string) *DataShareSessionCreate {
	if v != nil {
		_c.SetQualityStatus(*v)
	}
	return _c
}

// SetQualityErrors sets the "quality_errors" field.
func (_c *DataShareSessionCreate) SetQualityErrors(v []string) *DataShareSessionCreate {
	_c.mutation.SetQualityErrors(v)
	return _c
}

// SetStorageBytes sets the "storage_bytes" field.
func (_c *DataShareSessionCreate) SetStorageBytes(v int64) *DataShareSessionCreate {
	_c.mutation.SetStorageBytes(v)
	return _c
}

// SetNillableStorageBytes sets the "storage_bytes" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableStorageBytes(v *int64) *DataShareSessionCreate {
	if v != nil {
		_c.SetStorageBytes(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *DataShareSessionCreate) SetInputTokens(v int64) *DataShareSessionCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableInputTokens(v *int64) *DataShareSessionCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *DataShareSessionCreate) SetOutputTokens(v int64) *DataShareSessionCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableOutputTokens(v *int64) *DataShareSessionCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *DataShareSessionCreate) SetTotalTokens(v int64) *DataShareSessionCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableTotalTokens(v *int64) *DataShareSessionCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetActualCost sets the "actual_cost" field.
func (_c *DataShareSessionCreate) SetActualCost(v float64) *DataShareSessionCreate {
	_c.mutation.SetActualCost(v)
	return _c
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableActualCost(v *float64) *DataShareSessionCreate {
	if v != nil {
		_c.SetActualCost(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DataShareSessionCreate) SetUserID(v int64) *DataShareSessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *DataShareSessionCreate) SetAPIKeyID(v int64) *DataShareSessionCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *DataShareSessionCreate) SetGroupID(v int64) *DataShareSessionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DataShareSessionCreate) SetCreatedAt(v time.Time) *DataShareSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableCreatedAt(v *time.Time) *DataShareSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *DataShareSessionCreate) SetEndedAt(v time.Time) *DataShareSessionCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableEndedAt(v *time.Time) *DataShareSessionCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DataShareSessionCreate) SetUpdatedAt(v time.Time) *DataShareSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DataShareSessionCreate) SetNillableUpdatedAt(v *time.Time) *DataShareSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DataShareSessionMutation object of the builder.
func (_c *DataShareSessionCreate) Mutation() *DataShareSessionMutation {
	return _c.mutation
}

// Save creates the DataShareSession in the database.
func (_c *DataShareSessionCreate) Save(ctx context.Context) (*DataShareSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DataShareSessionCreate) SaveX(ctx context.Context) *DataShareSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DataShareSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DataShareSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DataShareSessionCreate) defaults() {
	if _, ok := _c.mutation.RequestPath(); !ok {
		v := datasharesession.DefaultRequestPath
		_c.mutation.SetRequestPath(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := datasharesession.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := datasharesession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IsFinalSnapshot(); !ok {
		v := datasharesession.DefaultIsFinalSnapshot
		_c.mutation.SetIsFinalSnapshot(v)
	}
	if _, ok := _c.mutation.SourceRequestCount(); !ok {
		v := datasharesession.DefaultSourceRequestCount
		_c.mutation.SetSourceRequestCount(v)
	}
	if _, ok := _c.mutation.PayloadEncoding(); !ok {
		v := datasharesession.DefaultPayloadEncoding
		_c.mutation.SetPayloadEncoding(v)
	}
	if _, ok := _c.mutation.PayloadBytes(); !ok {
		v := datasharesession.DefaultPayloadBytes
		_c.mutation.SetPayloadBytes(v)
	}
	if _, ok := _c.mutation.Exportable(); !ok {
		v := datasharesession.DefaultExportable
		_c.mutation.SetExportable(v)
	}
	if _, ok := _c.mutation.QualityStatus(); !ok {
		v := datasharesession.DefaultQualityStatus
		_c.mutation.SetQualityStatus(v)
	}
	if _, ok := _c.mutation.StorageBytes(); !ok {
		v := datasharesession.DefaultStorageBytes
		_c.mutation.SetStorageBytes(v)
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := datasharesession.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := datasharesession.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		v := datasharesession.DefaultTotalTokens
		_c.mutation.SetTotalTokens(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := datasharesession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := datasharesession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DataShareSessionCreate) check() error {
	if _, ok := _c.mutation.TrajectoryID(); !ok {
		return &ValidationError{Name: "trajectory_id", err: errors.New(`ent: missing required field "DataShareSession.trajectory_id"`)}
	}
	if v, ok := _c.mutation.TrajectoryID(); ok {
		if err := datasharesession.TrajectoryIDValidator(v); err != nil {
			return &ValidationError{Name: "trajectory_id", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.trajectory_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "DataShareSession.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := datasharesession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Dataset(); !ok {
		return &ValidationError{Name: "dataset", err: errors.New(`ent: missing required field "DataShareSession.dataset"`)}
	}
	if v, ok := _c.mutation.Dataset(); ok {
		if err := datasharesession.DatasetValidator(v); err != nil {
			return &ValidationError{Name: "dataset", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.dataset": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "DataShareSession.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := datasharesession.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "DataShareSession.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := datasharesession.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestPath(); !ok {
		return &ValidationError{Name: "request_path", err: errors.New(`ent: missing required field "DataShareSession.request_path"`)}
	}
	if v, ok := _c.mutation.RequestPath(); ok {
		if err := datasharesession.RequestPathValidator(v); err != nil {
			return &ValidationError{Name: "request_path", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.request_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "DataShareSession.user_agent"`)}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := datasharesession.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.user_agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DataShareSession.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := datasharesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsFinalSnapshot(); !ok {
		return &ValidationError{Name: "is_final_snapshot", err: errors.New(`ent: missing required field "DataShareSession.is_final_snapshot"`)}
	}
	if _, ok := _c.mutation.SourceRequestCount(); !ok {
		return &ValidationError{Name: "source_request_count", err: errors.New(`ent: missing required field "DataShareSession.source_request_count"`)}
	}
	if _, ok := _c.mutation.PayloadEncoding(); !ok {
		return &ValidationError{Name: "payload_encoding", err: errors.New(`ent: missing required field "DataShareSession.payload_encoding"`)}
	}
	if v, ok := _c.mutation.PayloadEncoding(); ok {
		if err := datasharesession.PayloadEncodingValidator(v); err != nil {
			return &ValidationError{Name: "payload_encoding", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.payload_encoding": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PayloadBytes(); !ok {
		return &ValidationError{Name: "payload_bytes", err: errors.New(`ent: missing required field "DataShareSession.payload_bytes"`)}
	}
	if _, ok := _c.mutation.Exportable(); !ok {
		return &ValidationError{Name: "exportable", err: errors.New(`ent: missing required field "DataShareSession.exportable"`)}
	}
	if _, ok := _c.mutation.QualityStatus(); !ok {
		return &ValidationError{Name: "quality_status", err: errors.New(`ent: missing required field "DataShareSession.quality_status"`)}
	}
	if v, ok := _c.mutation.QualityStatus(); ok {
		if err := datasharesession.QualityStatusValidator(v); err != nil {
			return &ValidationError{Name: "quality_status", err: fmt.Errorf(`ent: validator failed for field "DataShareSession.quality_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StorageBytes(); !ok {
		return &ValidationError{Name: "storage_bytes", err: errors.New(`ent: missing required field "DataShareSession.storage_bytes"`)}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "DataShareSession.input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "DataShareSession.output_tokens"`)}
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		return &ValidationError{Name: "total_tokens", err: errors.New(`ent: missing required field "DataShareSession.total_tokens"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DataShareSession.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "DataShareSession.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "DataShareSession.group_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DataShareSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DataShareSession.updated_at"`)}
	}
	return nil
}

func (_c *DataShareSessionCreate) sqlSave(ctx context.Context) (*DataShareSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DataShareSessionCreate) createSpec() (*DataShareSession, *sqlgraph.CreateSpec) {
	var (
		_node = &DataShareSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(datasharesession.Table, sqlgraph.NewFieldSpec(datasharesession.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TrajectoryID(); ok {
		_spec.SetField(datasharesession.FieldTrajectoryID, field.TypeString, value)
		_node.TrajectoryID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(datasharesession.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.Dataset(); ok {
		_spec.SetField(datasharesession.FieldDataset, field.TypeString, value)
		_node.Dataset = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(datasharesession.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(datasharesession.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.RequestPath(); ok {
		_spec.SetField(datasharesession.FieldRequestPath, field.TypeString, value)
		_node.RequestPath = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(datasharesession.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(datasharesession.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IsFinalSnapshot(); ok {
		_spec.SetField(datasharesession.FieldIsFinalSnapshot, field.TypeBool, value)
		_node.IsFinalSnapshot = value
	}
	if value, ok := _c.mutation.SourceRequestCount(); ok {
		_spec.SetField(datasharesession.FieldSourceRequestCount, field.TypeInt, value)
		_node.SourceRequestCount = value
	}
	if value, ok := _c.mutation.SystemPrompt(); ok {
		_spec.SetField(datasharesession.FieldSystemPrompt, field.TypeString, value)
		_node.SystemPrompt = &value
	}
	if value, ok := _c.mutation.Tools(); ok {
		_spec.SetField(datasharesession.FieldTools, field.TypeJSON, value)
		_node.Tools = value
	}
	if value, ok := _c.mutation.Messages(); ok {
		_spec.SetField(datasharesession.FieldMessages, field.TypeJSON, value)
		_node.Messages = value
	}
	if value, ok := _c.mutation.Usage(); ok {
		_spec.SetField(datasharesession.FieldUsage, field.TypeJSON, value)
		_node.Usage = value
	}
	if value, ok := _c.mutation.Meta(); ok {
		_spec.SetField(datasharesession.FieldMeta, field.TypeJSON, value)
		_node.Meta = value
	}
	if value, ok := _c.mutation.SessionJSON(); ok {
		_spec.SetField(datasharesession.FieldSessionJSON, field.TypeJSON, value)
		_node.SessionJSON = value
	}
	if value, ok := _c.mutation.PayloadCompressed(); ok {
		_spec.SetField(datasharesession.FieldPayloadCompressed, field.TypeBytes, value)
		_node.PayloadCompressed = &value
	}
	if value, ok := _c.mutation.PayloadEncoding(); ok {
		_spec.SetField(datasharesession.FieldPayloadEncoding, field.TypeString, value)
		_node.PayloadEncoding = value
	}
	if value, ok := _c.mutation.PayloadBytes(); ok {
		_spec.SetField(datasharesession.FieldPayloadBytes, field.TypeInt64, value)
		_node.PayloadBytes = value
	}
	if value, ok := _c.mutation.Exportable(); ok {
		_spec.SetField(datasharesession.FieldExportable, field.TypeBool, value)
		_node.Exportable = value
	}
	if value, ok := _c.mutation.QualityStatus(); ok {
		_spec.SetField(datasharesession.FieldQualityStatus, field.TypeString, value)
		_node.QualityStatus = value
	}
	if value, ok := _c.mutation.QualityErrors(); ok {
		_spec.SetField(datasharesession.FieldQualityErrors, field.TypeJSON, value)
		_node.QualityErrors = value
	}
	if value, ok := _c.mutation.StorageBytes(); ok {
		_spec.SetField(datasharesession.FieldStorageBytes, field.TypeInt64, value)
		_node.StorageBytes = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(datasharesession.FieldInputTokens, field.TypeInt64, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(datasharesession.FieldOutputTokens, field.TypeInt64, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(datasharesession.FieldTotalTokens, field.TypeInt64, value)
		_node.TotalTokens = value
	}
	if value, ok := _c.mutation.ActualCost(); ok {
		_spec.SetField(datasharesession.FieldActualCost, field.TypeFloat64, value)
		_node.ActualCost = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(datasharesession.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(datasharesession.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(datasharesession.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(datasharesession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(datasharesession.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(datasharesession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DataShareSession.Create().
//		SetTrajectoryID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DataShareSessionUpsert) {
//			SetTrajectoryID(v+v).
//		}).
//		Exec(ctx)
func (_c *DataShareSessionCreate) OnConflict(opts ...sql.ConflictOption) *DataShareSessionUpsertOne {
	_c.conflict = opts
	return &DataShareSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DataShareSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DataShareSessionCreate) OnConflictColumns(columns ...string) *DataShareSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DataShareSessionUpsertOne{
		create: _c,
	}
}

type (
	// DataShareSessionUpsertOne is the builder for "upsert"-ing
	//  one DataShareSession node.
	DataShareSessionUpsertOne struct {
		create *DataShareSessionCreate
	}

	// DataShareSessionUpsert is the "OnConflict" setter.
	DataShareSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTrajectoryID sets the "trajectory_id" field.
func (u *DataShareSessionUpsert) SetTrajectoryID(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldTrajectoryID, v)
	return u
}

// UpdateTrajectoryID sets the "trajectory_id" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateTrajectoryID() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldTrajectoryID)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *DataShareSessionUpsert) SetSessionID(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateSessionID() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldSessionID)
	return u
}

// SetDataset sets the "dataset" field.
func (u *DataShareSessionUpsert) SetDataset(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldDataset, v)
	return u
}

// UpdateDataset sets the "dataset" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateDataset() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldDataset)
	return u
}

// SetProvider sets the "provider" field.
func (u *DataShareSessionUpsert) SetProvider(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateProvider() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldProvider)
	return u
}

// SetModel sets the "model" field.
func (u *DataShareSessionUpsert) SetModel(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateModel() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldModel)
	return u
}

// SetRequestPath sets the "request_path" field.
func (u *DataShareSessionUpsert) SetRequestPath(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldRequestPath, v)
	return u
}

// UpdateRequestPath sets the "request_path" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateRequestPath() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldRequestPath)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *DataShareSessionUpsert) SetUserAgent(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateUserAgent() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldUserAgent)
	return u
}

// SetStatus sets the "status" field.
func (u *DataShareSessionUpsert) SetStatus(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateStatus() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldStatus)
	return u
}

// SetIsFinalSnapshot sets the "is_final_snapshot" field.
func (u *DataShareSessionUpsert) SetIsFinalSnapshot(v bool) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldIsFinalSnapshot, v)
	return u
}

// UpdateIsFinalSnapshot sets the "is_final_snapshot" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateIsFinalSnapshot() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldIsFinalSnapshot)
	return u
}

// SetSourceRequestCount sets the "source_request_count" field.
func (u *DataShareSessionUpsert) SetSourceRequestCount(v int) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldSourceRequestCount, v)
	return u
}

// UpdateSourceRequestCount sets the "source_request_count" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateSourceRequestCount() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldSourceRequestCount)
	return u
}

// AddSourceRequestCount adds v to the "source_request_count" field.
func (u *DataShareSessionUpsert) AddSourceRequestCount(v int) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldSourceRequestCount, v)
	return u
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *DataShareSessionUpsert) SetSystemPrompt(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldSystemPrompt, v)
	return u
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateSystemPrompt() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldSystemPrompt)
	return u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (u *DataShareSessionUpsert) ClearSystemPrompt() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldSystemPrompt)
	return u
}

// SetTools sets the "tools" field.
func (u *DataShareSessionUpsert) SetTools(v []map[string]interface{}) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldTools, v)
	return u
}

// UpdateTools sets the "tools" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateTools() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldTools)
	return u
}

// ClearTools clears the value of the "tools" field.
func (u *DataShareSessionUpsert) ClearTools() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldTools)
	return u
}

// SetMessages sets the "messages" field.
func (u *DataShareSessionUpsert) SetMessages(v []map[string]interface{}) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldMessages, v)
	return u
}

// UpdateMessages sets the "messages" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateMessages() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldMessages)
	return u
}

// ClearMessages clears the value of the "messages" field.
func (u *DataShareSessionUpsert) ClearMessages() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldMessages)
	return u
}

// SetUsage sets the "usage" field.
func (u *DataShareSessionUpsert) SetUsage(v map[string]interface{}) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldUsage, v)
	return u
}

// UpdateUsage sets the "usage" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateUsage() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldUsage)
	return u
}

// ClearUsage clears the value of the "usage" field.
func (u *DataShareSessionUpsert) ClearUsage() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldUsage)
	return u
}

// SetMeta sets the "meta" field.
func (u *DataShareSessionUpsert) SetMeta(v map[string]interface{}) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldMeta, v)
	return u
}

// UpdateMeta sets the "meta" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateMeta() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldMeta)
	return u
}

// ClearMeta clears the value of the "meta" field.
func (u *DataShareSessionUpsert) ClearMeta() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldMeta)
	return u
}

// SetSessionJSON sets the "session_json" field.
func (u *DataShareSessionUpsert) SetSessionJSON(v map[string]interface{}) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldSessionJSON, v)
	return u
}

// UpdateSessionJSON sets the "session_json" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateSessionJSON() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldSessionJSON)
	return u
}

// ClearSessionJSON clears the value of the "session_json" field.
func (u *DataShareSessionUpsert) ClearSessionJSON() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldSessionJSON)
	return u
}

// SetPayloadCompressed sets the "payload_compressed" field.
func (u *DataShareSessionUpsert) SetPayloadCompressed(v []byte) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldPayloadCompressed, v)
	return u
}

// UpdatePayloadCompressed sets the "payload_compressed" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdatePayloadCompressed() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldPayloadCompressed)
	return u
}

// ClearPayloadCompressed clears the value of the "payload_compressed" field.
func (u *DataShareSessionUpsert) ClearPayloadCompressed() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldPayloadCompressed)
	return u
}

// SetPayloadEncoding sets the "payload_encoding" field.
func (u *DataShareSessionUpsert) SetPayloadEncoding(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldPayloadEncoding, v)
	return u
}

// UpdatePayloadEncoding sets the "payload_encoding" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdatePayloadEncoding() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldPayloadEncoding)
	return u
}

// SetPayloadBytes sets the "payload_bytes" field.
func (u *DataShareSessionUpsert) SetPayloadBytes(v int64) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldPayloadBytes, v)
	return u
}

// UpdatePayloadBytes sets the "payload_bytes" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdatePayloadBytes() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldPayloadBytes)
	return u
}

// AddPayloadBytes adds v to the "payload_bytes" field.
func (u *DataShareSessionUpsert) AddPayloadBytes(v int64) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldPayloadBytes, v)
	return u
}

// SetExportable sets the "exportable" field.
func (u *DataShareSessionUpsert) SetExportable(v bool) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldExportable, v)
	return u
}

// UpdateExportable sets the "exportable" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateExportable() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldExportable)
	return u
}

// SetQualityStatus sets the "quality_status" field.
func (u *DataShareSessionUpsert) SetQualityStatus(v string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldQualityStatus, v)
	return u
}

// UpdateQualityStatus sets the "quality_status" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateQualityStatus() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldQualityStatus)
	return u
}

// SetQualityErrors sets the "quality_errors" field.
func (u *DataShareSessionUpsert) SetQualityErrors(v []string) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldQualityErrors, v)
	return u
}

// UpdateQualityErrors sets the "quality_errors" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateQualityErrors() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldQualityErrors)
	return u
}

// ClearQualityErrors clears the value of the "quality_errors" field.
func (u *DataShareSessionUpsert) ClearQualityErrors() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldQualityErrors)
	return u
}

// SetStorageBytes sets the "storage_bytes" field.
func (u *DataShareSessionUpsert) SetStorageBytes(v int64) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldStorageBytes, v)
	return u
}

// UpdateStorageBytes sets the "storage_bytes" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateStorageBytes() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldStorageBytes)
	return u
}

// AddStorageBytes adds v to the "storage_bytes" field.
func (u *DataShareSessionUpsert) AddStorageBytes(v int64) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldStorageBytes, v)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *DataShareSessionUpsert) SetInputTokens(v int64) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateInputTokens() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *DataShareSessionUpsert) AddInputTokens(v int64) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldInputTokens, v)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *DataShareSessionUpsert) SetOutputTokens(v int64) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateOutputTokens() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *DataShareSessionUpsert) AddOutputTokens(v int64) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldOutputTokens, v)
	return u
}

// SetTotalTokens sets the "total_tokens" field.
func (u *DataShareSessionUpsert) SetTotalTokens(v int64) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldTotalTokens, v)
	return u
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateTotalTokens() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldTotalTokens)
	return u
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *DataShareSessionUpsert) AddTotalTokens(v int64) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldTotalTokens, v)
	return u
}

// SetActualCost sets the "actual_cost" field.
func (u *DataShareSessionUpsert) SetActualCost(v float64) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldActualCost, v)
	return u
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateActualCost() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldActualCost)
	return u
}

// AddActualCost adds v to the "actual_cost" field.
func (u *DataShareSessionUpsert) AddActualCost(v float64) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldActualCost, v)
	return u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *DataShareSessionUpsert) ClearActualCost() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldActualCost)
	return u
}

// SetUserID sets the "user_id" field.
func (u *DataShareSessionUpsert) SetUserID(v int64) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateUserID() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *DataShareSessionUpsert) AddUserID(v int64) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *DataShareSessionUpsert) SetAPIKeyID(v int64) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateAPIKeyID() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *DataShareSessionUpsert) AddAPIKeyID(v int64) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldAPIKeyID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *DataShareSessionUpsert) SetGroupID(v int64) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateGroupID() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *DataShareSessionUpsert) AddGroupID(v int64) *DataShareSessionUpsert {
	u.Add(datasharesession.FieldGroupID, v)
	return u
}

// SetEndedAt sets the "ended_at" field.
func (u *DataShareSessionUpsert) SetEndedAt(v time.Time) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldEndedAt, v)
	return u
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateEndedAt() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldEndedAt)
	return u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *DataShareSessionUpsert) ClearEndedAt() *DataShareSessionUpsert {
	u.SetNull(datasharesession.FieldEndedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DataShareSessionUpsert) SetUpdatedAt(v time.Time) *DataShareSessionUpsert {
	u.Set(datasharesession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DataShareSessionUpsert) UpdateUpdatedAt() *DataShareSessionUpsert {
	u.SetExcluded(datasharesession.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DataShareSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DataShareSessionUpsertOne) UpdateNewValues() *DataShareSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(datasharesession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DataShareSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DataShareSessionUpsertOne) Ignore() *DataShareSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DataShareSessionUpsertOne) DoNothing() *DataShareSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DataShareSessionCreate.OnConflict
// documentation for more info.
func (u *DataShareSessionUpsertOne) Update(set func(*DataShareSessionUpsert)) *DataShareSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DataShareSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTrajectoryID sets the "trajectory_id" field.
func (u *DataShareSessionUpsertOne) SetTrajectoryID(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetTrajectoryID(v)
	})
}

// UpdateTrajectoryID sets the "trajectory_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateTrajectoryID() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateTrajectoryID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *DataShareSessionUpsertOne) SetSessionID(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateSessionID() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateSessionID()
	})
}

// SetDataset sets the "dataset" field.
func (u *DataShareSessionUpsertOne) SetDataset(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetDataset(v)
	})
}

// UpdateDataset sets the "dataset" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateDataset() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateDataset()
	})
}

// SetProvider sets the "provider" field.
func (u *DataShareSessionUpsertOne) SetProvider(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateProvider() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *DataShareSessionUpsertOne) SetModel(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateModel() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateModel()
	})
}

// SetRequestPath sets the "request_path" field.
func (u *DataShareSessionUpsertOne) SetRequestPath(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetRequestPath(v)
	})
}

// UpdateRequestPath sets the "request_path" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateRequestPath() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateRequestPath()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *DataShareSessionUpsertOne) SetUserAgent(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateUserAgent() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateUserAgent()
	})
}

// SetStatus sets the "status" field.
func (u *DataShareSessionUpsertOne) SetStatus(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateStatus() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetIsFinalSnapshot sets the "is_final_snapshot" field.
func (u *DataShareSessionUpsertOne) SetIsFinalSnapshot(v bool) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetIsFinalSnapshot(v)
	})
}

// UpdateIsFinalSnapshot sets the "is_final_snapshot" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateIsFinalSnapshot() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateIsFinalSnapshot()
	})
}

// SetSourceRequestCount sets the "source_request_count" field.
func (u *DataShareSessionUpsertOne) SetSourceRequestCount(v int) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetSourceRequestCount(v)
	})
}

// AddSourceRequestCount adds v to the "source_request_count" field.
func (u *DataShareSessionUpsertOne) AddSourceRequestCount(v int) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddSourceRequestCount(v)
	})
}

// UpdateSourceRequestCount sets the "source_request_count" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateSourceRequestCount() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateSourceRequestCount()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *DataShareSessionUpsertOne) SetSystemPrompt(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateSystemPrompt() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateSystemPrompt()
	})
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (u *DataShareSessionUpsertOne) ClearSystemPrompt() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearSystemPrompt()
	})
}

// SetTools sets the "tools" field.
func (u *DataShareSessionUpsertOne) SetTools(v []map[string]interface{}) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetTools(v)
	})
}

// UpdateTools sets the "tools" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateTools() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateTools()
	})
}

// ClearTools clears the value of the "tools" field.
func (u *DataShareSessionUpsertOne) ClearTools() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearTools()
	})
}

// SetMessages sets the "messages" field.
func (u *DataShareSessionUpsertOne) SetMessages(v []map[string]interface{}) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetMessages(v)
	})
}

// UpdateMessages sets the "messages" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateMessages() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateMessages()
	})
}

// ClearMessages clears the value of the "messages" field.
func (u *DataShareSessionUpsertOne) ClearMessages() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearMessages()
	})
}

// SetUsage sets the "usage" field.
func (u *DataShareSessionUpsertOne) SetUsage(v map[string]interface{}) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetUsage(v)
	})
}

// UpdateUsage sets the "usage" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateUsage() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateUsage()
	})
}

// ClearUsage clears the value of the "usage" field.
func (u *DataShareSessionUpsertOne) ClearUsage() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearUsage()
	})
}

// SetMeta sets the "meta" field.
func (u *DataShareSessionUpsertOne) SetMeta(v map[string]interface{}) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetMeta(v)
	})
}

// UpdateMeta sets the "meta" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateMeta() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateMeta()
	})
}

// ClearMeta clears the value of the "meta" field.
func (u *DataShareSessionUpsertOne) ClearMeta() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearMeta()
	})
}

// SetSessionJSON sets the "session_json" field.
func (u *DataShareSessionUpsertOne) SetSessionJSON(v map[string]interface{}) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetSessionJSON(v)
	})
}

// UpdateSessionJSON sets the "session_json" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateSessionJSON() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateSessionJSON()
	})
}

// ClearSessionJSON clears the value of the "session_json" field.
func (u *DataShareSessionUpsertOne) ClearSessionJSON() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearSessionJSON()
	})
}

// SetPayloadCompressed sets the "payload_compressed" field.
func (u *DataShareSessionUpsertOne) SetPayloadCompressed(v []byte) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetPayloadCompressed(v)
	})
}

// UpdatePayloadCompressed sets the "payload_compressed" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdatePayloadCompressed() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdatePayloadCompressed()
	})
}

// ClearPayloadCompressed clears the value of the "payload_compressed" field.
func (u *DataShareSessionUpsertOne) ClearPayloadCompressed() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearPayloadCompressed()
	})
}

// SetPayloadEncoding sets the "payload_encoding" field.
func (u *DataShareSessionUpsertOne) SetPayloadEncoding(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetPayloadEncoding(v)
	})
}

// UpdatePayloadEncoding sets the "payload_encoding" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdatePayloadEncoding() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdatePayloadEncoding()
	})
}

// SetPayloadBytes sets the "payload_bytes" field.
func (u *DataShareSessionUpsertOne) SetPayloadBytes(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetPayloadBytes(v)
	})
}

// AddPayloadBytes adds v to the "payload_bytes" field.
func (u *DataShareSessionUpsertOne) AddPayloadBytes(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddPayloadBytes(v)
	})
}

// UpdatePayloadBytes sets the "payload_bytes" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdatePayloadBytes() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdatePayloadBytes()
	})
}

// SetExportable sets the "exportable" field.
func (u *DataShareSessionUpsertOne) SetExportable(v bool) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetExportable(v)
	})
}

// UpdateExportable sets the "exportable" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateExportable() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateExportable()
	})
}

// SetQualityStatus sets the "quality_status" field.
func (u *DataShareSessionUpsertOne) SetQualityStatus(v string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetQualityStatus(v)
	})
}

// UpdateQualityStatus sets the "quality_status" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateQualityStatus() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateQualityStatus()
	})
}

// SetQualityErrors sets the "quality_errors" field.
func (u *DataShareSessionUpsertOne) SetQualityErrors(v []string) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetQualityErrors(v)
	})
}

// UpdateQualityErrors sets the "quality_errors" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateQualityErrors() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateQualityErrors()
	})
}

// ClearQualityErrors clears the value of the "quality_errors" field.
func (u *DataShareSessionUpsertOne) ClearQualityErrors() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearQualityErrors()
	})
}

// SetStorageBytes sets the "storage_bytes" field.
func (u *DataShareSessionUpsertOne) SetStorageBytes(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetStorageBytes(v)
	})
}

// AddStorageBytes adds v to the "storage_bytes" field.
func (u *DataShareSessionUpsertOne) AddStorageBytes(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddStorageBytes(v)
	})
}

// UpdateStorageBytes sets the "storage_bytes" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateStorageBytes() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateStorageBytes()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *DataShareSessionUpsertOne) SetInputTokens(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *DataShareSessionUpsertOne) AddInputTokens(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateInputTokens() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *DataShareSessionUpsertOne) SetOutputTokens(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *DataShareSessionUpsertOne) AddOutputTokens(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateOutputTokens() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *DataShareSessionUpsertOne) SetTotalTokens(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *DataShareSessionUpsertOne) AddTotalTokens(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateTotalTokens() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *DataShareSessionUpsertOne) SetActualCost(v float64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *DataShareSessionUpsertOne) AddActualCost(v float64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateActualCost() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateActualCost()
	})
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *DataShareSessionUpsertOne) ClearActualCost() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearActualCost()
	})
}

// SetUserID sets the "user_id" field.
func (u *DataShareSessionUpsertOne) SetUserID(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *DataShareSessionUpsertOne) AddUserID(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateUserID() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *DataShareSessionUpsertOne) SetAPIKeyID(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *DataShareSessionUpsertOne) AddAPIKeyID(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateAPIKeyID() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DataShareSessionUpsertOne) SetGroupID(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *DataShareSessionUpsertOne) AddGroupID(v int64) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateGroupID() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateGroupID()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *DataShareSessionUpsertOne) SetEndedAt(v time.Time) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateEndedAt() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *DataShareSessionUpsertOne) ClearEndedAt() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearEndedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DataShareSessionUpsertOne) SetUpdatedAt(v time.Time) *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DataShareSessionUpsertOne) UpdateUpdatedAt() *DataShareSessionUpsertOne {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DataShareSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DataShareSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DataShareSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DataShareSessionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DataShareSessionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DataShareSessionCreateBulk is the builder for creating many DataShareSession entities in bulk.
type DataShareSessionCreateBulk struct {
	config
	err      error
	builders []*DataShareSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the DataShareSession entities in the database.
func (_c *DataShareSessionCreateBulk) Save(ctx context.Context) ([]*DataShareSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DataShareSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DataShareSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DataShareSessionCreateBulk) SaveX(ctx context.Context) []*DataShareSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DataShareSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DataShareSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DataShareSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DataShareSessionUpsert) {
//			SetTrajectoryID(v+v).
//		}).
//		Exec(ctx)
func (_c *DataShareSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *DataShareSessionUpsertBulk {
	_c.conflict = opts
	return &DataShareSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DataShareSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DataShareSessionCreateBulk) OnConflictColumns(columns ...string) *DataShareSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DataShareSessionUpsertBulk{
		create: _c,
	}
}

// DataShareSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of DataShareSession nodes.
type DataShareSessionUpsertBulk struct {
	create *DataShareSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DataShareSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DataShareSessionUpsertBulk) UpdateNewValues() *DataShareSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(datasharesession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DataShareSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DataShareSessionUpsertBulk) Ignore() *DataShareSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DataShareSessionUpsertBulk) DoNothing() *DataShareSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DataShareSessionCreateBulk.OnConflict
// documentation for more info.
func (u *DataShareSessionUpsertBulk) Update(set func(*DataShareSessionUpsert)) *DataShareSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DataShareSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTrajectoryID sets the "trajectory_id" field.
func (u *DataShareSessionUpsertBulk) SetTrajectoryID(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetTrajectoryID(v)
	})
}

// UpdateTrajectoryID sets the "trajectory_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateTrajectoryID() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateTrajectoryID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *DataShareSessionUpsertBulk) SetSessionID(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateSessionID() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateSessionID()
	})
}

// SetDataset sets the "dataset" field.
func (u *DataShareSessionUpsertBulk) SetDataset(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetDataset(v)
	})
}

// UpdateDataset sets the "dataset" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateDataset() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateDataset()
	})
}

// SetProvider sets the "provider" field.
func (u *DataShareSessionUpsertBulk) SetProvider(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateProvider() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *DataShareSessionUpsertBulk) SetModel(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateModel() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateModel()
	})
}

// SetRequestPath sets the "request_path" field.
func (u *DataShareSessionUpsertBulk) SetRequestPath(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetRequestPath(v)
	})
}

// UpdateRequestPath sets the "request_path" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateRequestPath() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateRequestPath()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *DataShareSessionUpsertBulk) SetUserAgent(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateUserAgent() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateUserAgent()
	})
}

// SetStatus sets the "status" field.
func (u *DataShareSessionUpsertBulk) SetStatus(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateStatus() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetIsFinalSnapshot sets the "is_final_snapshot" field.
func (u *DataShareSessionUpsertBulk) SetIsFinalSnapshot(v bool) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetIsFinalSnapshot(v)
	})
}

// UpdateIsFinalSnapshot sets the "is_final_snapshot" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateIsFinalSnapshot() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateIsFinalSnapshot()
	})
}

// SetSourceRequestCount sets the "source_request_count" field.
func (u *DataShareSessionUpsertBulk) SetSourceRequestCount(v int) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetSourceRequestCount(v)
	})
}

// AddSourceRequestCount adds v to the "source_request_count" field.
func (u *DataShareSessionUpsertBulk) AddSourceRequestCount(v int) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddSourceRequestCount(v)
	})
}

// UpdateSourceRequestCount sets the "source_request_count" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateSourceRequestCount() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateSourceRequestCount()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *DataShareSessionUpsertBulk) SetSystemPrompt(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateSystemPrompt() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateSystemPrompt()
	})
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (u *DataShareSessionUpsertBulk) ClearSystemPrompt() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearSystemPrompt()
	})
}

// SetTools sets the "tools" field.
func (u *DataShareSessionUpsertBulk) SetTools(v []map[string]interface{}) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetTools(v)
	})
}

// UpdateTools sets the "tools" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateTools() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateTools()
	})
}

// ClearTools clears the value of the "tools" field.
func (u *DataShareSessionUpsertBulk) ClearTools() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearTools()
	})
}

// SetMessages sets the "messages" field.
func (u *DataShareSessionUpsertBulk) SetMessages(v []map[string]interface{}) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetMessages(v)
	})
}

// UpdateMessages sets the "messages" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateMessages() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateMessages()
	})
}

// ClearMessages clears the value of the "messages" field.
func (u *DataShareSessionUpsertBulk) ClearMessages() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearMessages()
	})
}

// SetUsage sets the "usage" field.
func (u *DataShareSessionUpsertBulk) SetUsage(v map[string]interface{}) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetUsage(v)
	})
}

// UpdateUsage sets the "usage" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateUsage() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateUsage()
	})
}

// ClearUsage clears the value of the "usage" field.
func (u *DataShareSessionUpsertBulk) ClearUsage() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearUsage()
	})
}

// SetMeta sets the "meta" field.
func (u *DataShareSessionUpsertBulk) SetMeta(v map[string]interface{}) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetMeta(v)
	})
}

// UpdateMeta sets the "meta" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateMeta() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateMeta()
	})
}

// ClearMeta clears the value of the "meta" field.
func (u *DataShareSessionUpsertBulk) ClearMeta() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearMeta()
	})
}

// SetSessionJSON sets the "session_json" field.
func (u *DataShareSessionUpsertBulk) SetSessionJSON(v map[string]interface{}) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetSessionJSON(v)
	})
}

// UpdateSessionJSON sets the "session_json" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateSessionJSON() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateSessionJSON()
	})
}

// ClearSessionJSON clears the value of the "session_json" field.
func (u *DataShareSessionUpsertBulk) ClearSessionJSON() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearSessionJSON()
	})
}

// SetPayloadCompressed sets the "payload_compressed" field.
func (u *DataShareSessionUpsertBulk) SetPayloadCompressed(v []byte) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetPayloadCompressed(v)
	})
}

// UpdatePayloadCompressed sets the "payload_compressed" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdatePayloadCompressed() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdatePayloadCompressed()
	})
}

// ClearPayloadCompressed clears the value of the "payload_compressed" field.
func (u *DataShareSessionUpsertBulk) ClearPayloadCompressed() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearPayloadCompressed()
	})
}

// SetPayloadEncoding sets the "payload_encoding" field.
func (u *DataShareSessionUpsertBulk) SetPayloadEncoding(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetPayloadEncoding(v)
	})
}

// UpdatePayloadEncoding sets the "payload_encoding" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdatePayloadEncoding() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdatePayloadEncoding()
	})
}

// SetPayloadBytes sets the "payload_bytes" field.
func (u *DataShareSessionUpsertBulk) SetPayloadBytes(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetPayloadBytes(v)
	})
}

// AddPayloadBytes adds v to the "payload_bytes" field.
func (u *DataShareSessionUpsertBulk) AddPayloadBytes(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddPayloadBytes(v)
	})
}

// UpdatePayloadBytes sets the "payload_bytes" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdatePayloadBytes() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdatePayloadBytes()
	})
}

// SetExportable sets the "exportable" field.
func (u *DataShareSessionUpsertBulk) SetExportable(v bool) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetExportable(v)
	})
}

// UpdateExportable sets the "exportable" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateExportable() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateExportable()
	})
}

// SetQualityStatus sets the "quality_status" field.
func (u *DataShareSessionUpsertBulk) SetQualityStatus(v string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetQualityStatus(v)
	})
}

// UpdateQualityStatus sets the "quality_status" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateQualityStatus() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateQualityStatus()
	})
}

// SetQualityErrors sets the "quality_errors" field.
func (u *DataShareSessionUpsertBulk) SetQualityErrors(v []string) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetQualityErrors(v)
	})
}

// UpdateQualityErrors sets the "quality_errors" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateQualityErrors() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateQualityErrors()
	})
}

// ClearQualityErrors clears the value of the "quality_errors" field.
func (u *DataShareSessionUpsertBulk) ClearQualityErrors() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearQualityErrors()
	})
}

// SetStorageBytes sets the "storage_bytes" field.
func (u *DataShareSessionUpsertBulk) SetStorageBytes(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetStorageBytes(v)
	})
}

// AddStorageBytes adds v to the "storage_bytes" field.
func (u *DataShareSessionUpsertBulk) AddStorageBytes(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddStorageBytes(v)
	})
}

// UpdateStorageBytes sets the "storage_bytes" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateStorageBytes() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateStorageBytes()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *DataShareSessionUpsertBulk) SetInputTokens(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *DataShareSessionUpsertBulk) AddInputTokens(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateInputTokens() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *DataShareSessionUpsertBulk) SetOutputTokens(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *DataShareSessionUpsertBulk) AddOutputTokens(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateOutputTokens() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *DataShareSessionUpsertBulk) SetTotalTokens(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *DataShareSessionUpsertBulk) AddTotalTokens(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateTotalTokens() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *DataShareSessionUpsertBulk) SetActualCost(v float64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *DataShareSessionUpsertBulk) AddActualCost(v float64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateActualCost() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateActualCost()
	})
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *DataShareSessionUpsertBulk) ClearActualCost() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearActualCost()
	})
}

// SetUserID sets the "user_id" field.
func (u *DataShareSessionUpsertBulk) SetUserID(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *DataShareSessionUpsertBulk) AddUserID(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateUserID() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *DataShareSessionUpsertBulk) SetAPIKeyID(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *DataShareSessionUpsertBulk) AddAPIKeyID(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateAPIKeyID() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DataShareSessionUpsertBulk) SetGroupID(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *DataShareSessionUpsertBulk) AddGroupID(v int64) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateGroupID() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateGroupID()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *DataShareSessionUpsertBulk) SetEndedAt(v time.Time) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateEndedAt() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *DataShareSessionUpsertBulk) ClearEndedAt() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.ClearEndedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DataShareSessionUpsertBulk) SetUpdatedAt(v time.Time) *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DataShareSessionUpsertBulk) UpdateUpdatedAt() *DataShareSessionUpsertBulk {
	return u.Update(func(s *DataShareSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DataShareSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DataShareSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DataShareSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DataShareSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
