// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
	"github.com/TokenFlux/TokenRouter/ent/subscriptionplan"
	"github.com/TokenFlux/TokenRouter/ent/subscriptionplangroup"
)

// SubscriptionPlanGroupUpdate is the builder for updating SubscriptionPlanGroup entities.
type SubscriptionPlanGroupUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionPlanGroupMutation
}

// Where appends a list predicates to the SubscriptionPlanGroupUpdate builder.
func (_u *SubscriptionPlanGroupUpdate) Where(ps ...predicate.SubscriptionPlanGroup) *SubscriptionPlanGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubscriptionPlanID sets the "subscription_plan_id" field.
func (_u *SubscriptionPlanGroupUpdate) SetSubscriptionPlanID(v int64) *SubscriptionPlanGroupUpdate {
	_u.mutation.SetSubscriptionPlanID(v)
	return _u
}

// SetNillableSubscriptionPlanID sets the "subscription_plan_id" field if the given value is not nil.
func (_u *SubscriptionPlanGroupUpdate) SetNillableSubscriptionPlanID(v *int64) *SubscriptionPlanGroupUpdate {
	if v != nil {
		_u.SetSubscriptionPlanID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionPlanGroupUpdate) SetGroupID(v int64) *SubscriptionPlanGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionPlanGroupUpdate) SetNillableGroupID(v *int64) *SubscriptionPlanGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSubscriptionPlan sets the "subscription_plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionPlanGroupUpdate) SetSubscriptionPlan(v *SubscriptionPlan) *SubscriptionPlanGroupUpdate {
	return _u.SetSubscriptionPlanID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionPlanGroupUpdate) SetGroup(v *Group) *SubscriptionPlanGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionPlanGroupMutation object of the builder.
func (_u *SubscriptionPlanGroupUpdate) Mutation() *SubscriptionPlanGroupMutation {
	return _u.mutation
}

// ClearSubscriptionPlan clears the "subscription_plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionPlanGroupUpdate) ClearSubscriptionPlan() *SubscriptionPlanGroupUpdate {
	_u.mutation.ClearSubscriptionPlan()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionPlanGroupUpdate) ClearGroup() *SubscriptionPlanGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionPlanGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionPlanGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPlanGroupUpdate) check() error {
	if _u.mutation.SubscriptionPlanCleared() && len(_u.mutation.SubscriptionPlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPlanGroup.subscription_plan"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPlanGroup.group"`)
	}
	return nil
}

func (_u *SubscriptionPlanGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionplangroup.Table, subscriptionplangroup.Columns, sqlgraph.NewFieldSpec(subscriptionplangroup.FieldSubscriptionPlanID, field.TypeInt64), sqlgraph.NewFieldSpec(subscriptionplangroup.FieldGroupID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SubscriptionPlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.SubscriptionPlanTable,
			Columns: []string{subscriptionplangroup.SubscriptionPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionPlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.SubscriptionPlanTable,
			Columns: []string{subscriptionplangroup.SubscriptionPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.GroupTable,
			Columns: []string{subscriptionplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.GroupTable,
			Columns: []string{subscriptionplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplangroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionPlanGroupUpdateOne is the builder for updating a single SubscriptionPlanGroup entity.
type SubscriptionPlanGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionPlanGroupMutation
}

// SetSubscriptionPlanID sets the "subscription_plan_id" field.
func (_u *SubscriptionPlanGroupUpdateOne) SetSubscriptionPlanID(v int64) *SubscriptionPlanGroupUpdateOne {
	_u.mutation.SetSubscriptionPlanID(v)
	return _u
}

// SetNillableSubscriptionPlanID sets the "subscription_plan_id" field if the given value is not nil.
func (_u *SubscriptionPlanGroupUpdateOne) SetNillableSubscriptionPlanID(v *int64) *SubscriptionPlanGroupUpdateOne {
	if v != nil {
		_u.SetSubscriptionPlanID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionPlanGroupUpdateOne) SetGroupID(v int64) *SubscriptionPlanGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionPlanGroupUpdateOne) SetNillableGroupID(v *int64) *SubscriptionPlanGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSubscriptionPlan sets the "subscription_plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionPlanGroupUpdateOne) SetSubscriptionPlan(v *SubscriptionPlan) *SubscriptionPlanGroupUpdateOne {
	return _u.SetSubscriptionPlanID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *SubscriptionPlanGroupUpdateOne) SetGroup(v *Group) *SubscriptionPlanGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the SubscriptionPlanGroupMutation object of the builder.
func (_u *SubscriptionPlanGroupUpdateOne) Mutation() *SubscriptionPlanGroupMutation {
	return _u.mutation
}

// ClearSubscriptionPlan clears the "subscription_plan" edge to the SubscriptionPlan entity.
func (_u *SubscriptionPlanGroupUpdateOne) ClearSubscriptionPlan() *SubscriptionPlanGroupUpdateOne {
	_u.mutation.ClearSubscriptionPlan()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *SubscriptionPlanGroupUpdateOne) ClearGroup() *SubscriptionPlanGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the SubscriptionPlanGroupUpdate builder.
func (_u *SubscriptionPlanGroupUpdateOne) Where(ps ...predicate.SubscriptionPlanGroup) *SubscriptionPlanGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionPlanGroupUpdateOne) Select(field string, fields ...string) *SubscriptionPlanGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionPlanGroup entity.
func (_u *SubscriptionPlanGroupUpdateOne) Save(ctx context.Context) (*SubscriptionPlanGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanGroupUpdateOne) SaveX(ctx context.Context) *SubscriptionPlanGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionPlanGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPlanGroupUpdateOne) check() error {
	if _u.mutation.SubscriptionPlanCleared() && len(_u.mutation.SubscriptionPlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPlanGroup.subscription_plan"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionPlanGroup.group"`)
	}
	return nil
}

func (_u *SubscriptionPlanGroupUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionPlanGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionplangroup.Table, subscriptionplangroup.Columns, sqlgraph.NewFieldSpec(subscriptionplangroup.FieldSubscriptionPlanID, field.TypeInt64), sqlgraph.NewFieldSpec(subscriptionplangroup.FieldGroupID, field.TypeInt64))
	if id, ok := _u.mutation.SubscriptionPlanID(); !ok {
		return nil, &ValidationError{Name: "subscription_plan_id", err: errors.New(`ent: missing "SubscriptionPlanGroup.subscription_plan_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "SubscriptionPlanGroup.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !subscriptionplangroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SubscriptionPlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.SubscriptionPlanTable,
			Columns: []string{subscriptionplangroup.SubscriptionPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionPlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.SubscriptionPlanTable,
			Columns: []string{subscriptionplangroup.SubscriptionPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.GroupTable,
			Columns: []string{subscriptionplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscriptionplangroup.GroupTable,
			Columns: []string{subscriptionplangroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionPlanGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplangroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
