// 兼容入口只委托任务模块，S15/S16 清理。
package service

import (
	native "github.com/TokenFlux/TokenRouter/internal/batchimage"
)

const BatchImageProviderGeminiAPI = native.BatchImageProviderGeminiAPI
const BatchImageProviderVertex = native.BatchImageProviderVertex
const BatchImageJobStatusCreated = native.BatchImageJobStatusCreated
const BatchImageJobStatusUploading = native.BatchImageJobStatusUploading
const BatchImageJobStatusSubmitted = native.BatchImageJobStatusSubmitted
const BatchImageJobStatusRunning = native.BatchImageJobStatusRunning
const BatchImageJobStatusIndexing = native.BatchImageJobStatusIndexing
const BatchImageJobStatusSettling = native.BatchImageJobStatusSettling
const BatchImageJobStatusCompleted = native.BatchImageJobStatusCompleted
const BatchImageJobStatusFailed = native.BatchImageJobStatusFailed
const BatchImageJobStatusCancelled = native.BatchImageJobStatusCancelled
const BatchImageJobStatusOutputDeleted = native.BatchImageJobStatusOutputDeleted
const BatchImageItemStatusPending = native.BatchImageItemStatusPending
const BatchImageItemStatusSuccess = native.BatchImageItemStatusSuccess
const BatchImageItemStatusFailed = native.BatchImageItemStatusFailed
const BatchImageItemStatusCancelled = native.BatchImageItemStatusCancelled

var ErrBatchImageJobNotFound = native.ErrBatchImageJobNotFound
var ErrBatchImageJobExists = native.ErrBatchImageJobExists
var ErrBatchImageItemExists = native.ErrBatchImageItemExists
var ErrBatchImageInvalidTransition = native.ErrBatchImageInvalidTransition
var ErrBatchImageInvalidProvider = native.ErrBatchImageInvalidProvider
var ErrBatchImageMissingProviderJobName = native.ErrBatchImageMissingProviderJobName
var ErrBatchImageMissingAccountID = native.ErrBatchImageMissingAccountID
var ErrBatchImageUnsupportedProvider = native.ErrBatchImageUnsupportedProvider
var ErrBatchImageIndexOutputMissing = native.ErrBatchImageIndexOutputMissing
var ErrBatchImageIndexParseFailed = native.ErrBatchImageIndexParseFailed
var ErrBatchImageIndexNoResultLines = native.ErrBatchImageIndexNoResultLines
var ErrBatchImageDuplicateCustomID = native.ErrBatchImageDuplicateCustomID
var ErrBatchImageIndexStateConflict = native.ErrBatchImageIndexStateConflict
var ErrBatchImageSettlementInvalidStatus = native.ErrBatchImageSettlementInvalidStatus
var ErrBatchImageSettlementManifestConflict = native.ErrBatchImageSettlementManifestConflict
var ErrBatchImageSettlementPricingMissing = native.ErrBatchImageSettlementPricingMissing
var ErrBatchImageSettlementBillingFailed = native.ErrBatchImageSettlementBillingFailed
var ErrBatchImageAlreadySettled = native.ErrBatchImageAlreadySettled
var ErrBatchImageSettlementMissingAPIKeyID = native.ErrBatchImageSettlementMissingAPIKeyID
var ErrBatchImageSettlementMissingAccountID = native.ErrBatchImageSettlementMissingAccountID
var ErrBatchImageSettlementInvalidCounts = native.ErrBatchImageSettlementInvalidCounts
var ErrBatchImageSettlementCostExceedsHold = native.ErrBatchImageSettlementCostExceedsHold
var ErrBatchImageBillingHoldFailed = native.ErrBatchImageBillingHoldFailed
var ErrBatchImageInsufficientBalance = native.ErrBatchImageInsufficientBalance
var ErrBatchImageDisabled = native.ErrBatchImageDisabled
var ErrBatchImageGroupDisabled = native.ErrBatchImageGroupDisabled
var ErrBatchImageInvalidModel = native.ErrBatchImageInvalidModel
var ErrBatchImageNoAccountAvailable = native.ErrBatchImageNoAccountAvailable
var ErrBatchImageInvalidItems = native.ErrBatchImageInvalidItems
var ErrBatchImageDuplicateCustomIDInRequest = native.ErrBatchImageDuplicateCustomIDInRequest
var ErrBatchImagePromptTooLong = native.ErrBatchImagePromptTooLong
var ErrBatchImageInvalidReferenceImage = native.ErrBatchImageInvalidReferenceImage
var ErrBatchImageTooManyReferenceImages = native.ErrBatchImageTooManyReferenceImages
var ErrBatchImageReferenceImagesTooLarge = native.ErrBatchImageReferenceImagesTooLarge
var ErrBatchImageTooManyOutputImages = native.ErrBatchImageTooManyOutputImages
var ErrBatchImageProviderSubmitFailed = native.ErrBatchImageProviderSubmitFailed
var ErrBatchImageQueueFailed = native.ErrBatchImageQueueFailed
var ErrBatchImageIdempotencyConflict = native.ErrBatchImageIdempotencyConflict
var ErrBatchImageCancelFailed = native.ErrBatchImageCancelFailed
var ErrBatchImageVertexGCSBucketMissing = native.ErrBatchImageVertexGCSBucketMissing
var ErrBatchImageNotReady = native.ErrBatchImageNotReady
var ErrBatchImageOutputDeleted = native.ErrBatchImageOutputDeleted
var ErrBatchImageItemNotFound = native.ErrBatchImageItemNotFound
var ErrBatchImageItemFailed = native.ErrBatchImageItemFailed
var ErrBatchImageResultMissing = native.ErrBatchImageResultMissing
var ErrBatchImageDownloadLimited = native.ErrBatchImageDownloadLimited
var ErrBatchImageDownloadFailed = native.ErrBatchImageDownloadFailed
var ErrBatchImageDownloadTooLarge = native.ErrBatchImageDownloadTooLarge
var ErrBatchImageItemImageIndexOutOfRange = native.ErrBatchImageItemImageIndexOutOfRange
var ErrBatchImageZipTooManyItems = native.ErrBatchImageZipTooManyItems
var ErrBatchImageOutputDeleteNotReady = native.ErrBatchImageOutputDeleteNotReady
var ErrBatchImageRecordDeleteNotReady = native.ErrBatchImageRecordDeleteNotReady
var ErrBatchImageCleanupFailed = native.ErrBatchImageCleanupFailed
var ErrBatchImageCleanupUnsafePath = native.ErrBatchImageCleanupUnsafePath
var ErrBatchImageProviderCleanupFailed = native.ErrBatchImageProviderCleanupFailed

type BatchImageJob = native.BatchImageJob
type CreateBatchImageJobParams = native.CreateBatchImageJobParams
type BatchImageItem = native.BatchImageItem
type CreateBatchImageItemParams = native.CreateBatchImageItemParams
type BatchImageItemFilter = native.BatchImageItemFilter
type BatchImageJobFilter = native.BatchImageJobFilter
type BatchImageCounts = native.BatchImageCounts
type UpdateBatchImageJobProviderSubmitParams = native.UpdateBatchImageJobProviderSubmitParams
type BatchImageTransitionOptions = native.BatchImageTransitionOptions
type MarkBatchImageJobSettledParams = native.MarkBatchImageJobSettledParams
type BatchImageEvent = native.BatchImageEvent
type BatchImageRepository = native.BatchImageRepository

func NewBatchImageID() (string, error) { return native.NewBatchImageID() }
func IsSupportedBatchImageProvider(provider string) bool {
	return native.IsSupportedBatchImageProvider(provider)
}
func IsTerminalBatchImageJobStatus(status string) bool {
	return native.IsTerminalBatchImageJobStatus(status)
}
func CanTransitionBatchImageJob(from, to string) bool {
	return native.CanTransitionBatchImageJob(from, to)
}
