package service

import (
	"github.com/TokenFlux/TokenRouter/internal/backup"
)

type DataManagementPostgresConfig = backup.DataManagementPostgresConfig
type DataManagementRedisConfig = backup.DataManagementRedisConfig
type DataManagementS3Config = backup.DataManagementS3Config
type DataManagementConfig = backup.DataManagementConfig
type DataManagementTestS3Result = backup.DataManagementTestS3Result
type DataManagementCreateBackupJobInput = backup.DataManagementCreateBackupJobInput
type DataManagementListBackupJobsInput = backup.DataManagementListBackupJobsInput
type DataManagementArtifactInfo = backup.DataManagementArtifactInfo
type DataManagementS3ObjectInfo = backup.DataManagementS3ObjectInfo
type DataManagementBackupJob = backup.DataManagementBackupJob
type DataManagementSourceProfile = backup.DataManagementSourceProfile
type DataManagementSourceConfig = backup.DataManagementSourceConfig
type DataManagementCreateSourceProfileInput = backup.DataManagementCreateSourceProfileInput
type DataManagementUpdateSourceProfileInput = backup.DataManagementUpdateSourceProfileInput
type DataManagementS3Profile = backup.DataManagementS3Profile
type DataManagementCreateS3ProfileInput = backup.DataManagementCreateS3ProfileInput
type DataManagementUpdateS3ProfileInput = backup.DataManagementUpdateS3ProfileInput
type DataManagementListBackupJobsResult = backup.DataManagementListBackupJobsResult
