// 本文件维护 service 的所属能力；兼容入口复用唯一实现。
package service

import (
	context "context"
	acctcore "github.com/TokenFlux/TokenRouter/internal/account"
)

const maxGrokOAuthReconcilePageSize = acctcore.MaxGrokOAuthReconcilePageSize
const GrokOAuthReconcileReasonMissingRefreshToken = acctcore.GrokOAuthReconcileReasonMissingRefreshToken
const GrokOAuthReconcileReasonMissingAccessToken = acctcore.GrokOAuthReconcileReasonMissingAccessToken
const GrokOAuthReconcileReasonMissingExpiry = acctcore.GrokOAuthReconcileReasonMissingExpiry
const GrokOAuthReconcileReasonInvalidExpiry = acctcore.GrokOAuthReconcileReasonInvalidExpiry
const GrokOAuthReconcileReasonNearExpiry = acctcore.GrokOAuthReconcileReasonNearExpiry
const GrokOAuthReconcileReasonCredentialRejected = acctcore.GrokOAuthReconcileReasonCredentialRejected
const GrokOAuthReconcileActionBlock = acctcore.GrokOAuthReconcileActionBlock
const GrokOAuthReconcileActionRefresh = acctcore.GrokOAuthReconcileActionRefresh
const GrokOAuthReconcileOutcomePlanned = acctcore.GrokOAuthReconcileOutcomePlanned
const GrokOAuthReconcileOutcomeApplied = acctcore.GrokOAuthReconcileOutcomeApplied
const GrokOAuthReconcileOutcomeSkipped = acctcore.GrokOAuthReconcileOutcomeSkipped
const GrokOAuthReconcileOutcomeFailed = acctcore.GrokOAuthReconcileOutcomeFailed
const GrokOAuthReconcileOutcomePartial = acctcore.GrokOAuthReconcileOutcomePartial

var ErrGrokOAuthReconcileMode = acctcore.ErrGrokOAuthReconcileMode
var ErrGrokOAuthReconcileCursor = acctcore.ErrGrokOAuthReconcileCursor
var ErrGrokOAuthReconcileLimit = acctcore.ErrGrokOAuthReconcileLimit
var ErrGrokOAuthReconcileWindow = acctcore.ErrGrokOAuthReconcileWindow

type GrokOAuthReconciler = acctcore.GrokOAuthReconciler
type GrokOAuthConditionalErrorRepository = acctcore.GrokOAuthConditionalErrorWriter
type GrokOAuthReconcileInput = acctcore.GrokOAuthReconcileInput
type GrokOAuthReconcileItem = acctcore.GrokOAuthReconcileItem
type GrokOAuthReconcileResult = acctcore.GrokOAuthReconcileResult

// ReconcileGrokOAuth 只委托账号所属的完整对账入口。
func (s *TokenRefreshService) ReconcileGrokOAuth(ctx context.Context, input GrokOAuthReconcileInput) (*GrokOAuthReconcileResult, error) {
	return s.Core().ReconcileGrokOAuth(ctx, input)
}
func (s *TokenRefreshService) grokOAuthReconcileMaxPageSize() int {
	return acctcore.MaxGrokOAuthReconcilePageSize
}
