// 本文件维护 service 的所属能力；兼容入口复用唯一实现。
package service

import (
	routing "github.com/TokenFlux/TokenRouter/internal/routing"
)

const defaultGroupAvailabilityProbeIntervalMinutes = routing.DefaultGroupAvailabilityProbeIntervalMinutes

const defaultGroupAvailabilityProbeTimeoutSeconds = routing.DefaultGroupAvailabilityProbeTimeoutSeconds

const defaultGroupAvailabilityProbeMaxRetries = routing.DefaultGroupAvailabilityProbeMaxRetries

const maxGroupAvailabilityProbeMaxRetries = routing.MaxGroupAvailabilityProbeMaxRetries

const maxGroupAvailabilityProbeUserAgentLength = routing.MaxGroupAvailabilityProbeUserAgentLength

const invalidGroupAvailabilityProbeConfigReason = routing.InvalidGroupAvailabilityProbeConfigReason

// normalizeGroupAvailabilityProbeConfig 委托所属模块的唯一实现。
func normalizeGroupAvailabilityProbeConfig(cfg GroupAvailabilityProbeConfig) (GroupAvailabilityProbeConfig, error) {
	return routing.NormalizeGroupAvailabilityProbeConfig(cfg)
}

// normalizeGroupAvailabilityProbeConfigForAdminWrite 委托所属模块的唯一实现。
func normalizeGroupAvailabilityProbeConfigForAdminWrite(cfg GroupAvailabilityProbeConfig) (GroupAvailabilityProbeConfig, error) {
	return routing.NormalizeGroupAvailabilityProbeConfigForAdminWrite(cfg)
}
