// Code generated by ent, DO NOT EDIT.

package datasharesession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/BrandonVee/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldID, id))
}

// TrajectoryID applies equality check predicate on the "trajectory_id" field. It's identical to TrajectoryIDEQ.
func TrajectoryID(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldTrajectoryID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldSessionID, v))
}

// Dataset applies equality check predicate on the "dataset" field. It's identical to DatasetEQ.
func Dataset(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldDataset, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldProvider, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldModel, v))
}

// RequestPath applies equality check predicate on the "request_path" field. It's identical to RequestPathEQ.
func RequestPath(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldRequestPath, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldUserAgent, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldStatus, v))
}

// IsFinalSnapshot applies equality check predicate on the "is_final_snapshot" field. It's identical to IsFinalSnapshotEQ.
func IsFinalSnapshot(v bool) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldIsFinalSnapshot, v))
}

// SourceRequestCount applies equality check predicate on the "source_request_count" field. It's identical to SourceRequestCountEQ.
func SourceRequestCount(v int) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldSourceRequestCount, v))
}

// SystemPrompt applies equality check predicate on the "system_prompt" field. It's identical to SystemPromptEQ.
func SystemPrompt(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldSystemPrompt, v))
}

// PayloadCompressed applies equality check predicate on the "payload_compressed" field. It's identical to PayloadCompressedEQ.
func PayloadCompressed(v []byte) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldPayloadCompressed, v))
}

// PayloadEncoding applies equality check predicate on the "payload_encoding" field. It's identical to PayloadEncodingEQ.
func PayloadEncoding(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldPayloadEncoding, v))
}

// PayloadBytes applies equality check predicate on the "payload_bytes" field. It's identical to PayloadBytesEQ.
func PayloadBytes(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldPayloadBytes, v))
}

// Exportable applies equality check predicate on the "exportable" field. It's identical to ExportableEQ.
func Exportable(v bool) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldExportable, v))
}

// QualityStatus applies equality check predicate on the "quality_status" field. It's identical to QualityStatusEQ.
func QualityStatus(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldQualityStatus, v))
}

// StorageBytes applies equality check predicate on the "storage_bytes" field. It's identical to StorageBytesEQ.
func StorageBytes(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldStorageBytes, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldOutputTokens, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldTotalTokens, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldActualCost, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldGroupID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldCreatedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldEndedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// TrajectoryIDEQ applies the EQ predicate on the "trajectory_id" field.
func TrajectoryIDEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldTrajectoryID, v))
}

// TrajectoryIDNEQ applies the NEQ predicate on the "trajectory_id" field.
func TrajectoryIDNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldTrajectoryID, v))
}

// TrajectoryIDIn applies the In predicate on the "trajectory_id" field.
func TrajectoryIDIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldTrajectoryID, vs...))
}

// TrajectoryIDNotIn applies the NotIn predicate on the "trajectory_id" field.
func TrajectoryIDNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldTrajectoryID, vs...))
}

// TrajectoryIDGT applies the GT predicate on the "trajectory_id" field.
func TrajectoryIDGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldTrajectoryID, v))
}

// TrajectoryIDGTE applies the GTE predicate on the "trajectory_id" field.
func TrajectoryIDGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldTrajectoryID, v))
}

// TrajectoryIDLT applies the LT predicate on the "trajectory_id" field.
func TrajectoryIDLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldTrajectoryID, v))
}

// TrajectoryIDLTE applies the LTE predicate on the "trajectory_id" field.
func TrajectoryIDLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldTrajectoryID, v))
}

// TrajectoryIDContains applies the Contains predicate on the "trajectory_id" field.
func TrajectoryIDContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldTrajectoryID, v))
}

// TrajectoryIDHasPrefix applies the HasPrefix predicate on the "trajectory_id" field.
func TrajectoryIDHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldTrajectoryID, v))
}

// TrajectoryIDHasSuffix applies the HasSuffix predicate on the "trajectory_id" field.
func TrajectoryIDHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldTrajectoryID, v))
}

// TrajectoryIDEqualFold applies the EqualFold predicate on the "trajectory_id" field.
func TrajectoryIDEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldTrajectoryID, v))
}

// TrajectoryIDContainsFold applies the ContainsFold predicate on the "trajectory_id" field.
func TrajectoryIDContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldTrajectoryID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldSessionID, v))
}

// DatasetEQ applies the EQ predicate on the "dataset" field.
func DatasetEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldDataset, v))
}

// DatasetNEQ applies the NEQ predicate on the "dataset" field.
func DatasetNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldDataset, v))
}

// DatasetIn applies the In predicate on the "dataset" field.
func DatasetIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldDataset, vs...))
}

// DatasetNotIn applies the NotIn predicate on the "dataset" field.
func DatasetNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldDataset, vs...))
}

// DatasetGT applies the GT predicate on the "dataset" field.
func DatasetGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldDataset, v))
}

// DatasetGTE applies the GTE predicate on the "dataset" field.
func DatasetGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldDataset, v))
}

// DatasetLT applies the LT predicate on the "dataset" field.
func DatasetLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldDataset, v))
}

// DatasetLTE applies the LTE predicate on the "dataset" field.
func DatasetLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldDataset, v))
}

// DatasetContains applies the Contains predicate on the "dataset" field.
func DatasetContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldDataset, v))
}

// DatasetHasPrefix applies the HasPrefix predicate on the "dataset" field.
func DatasetHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldDataset, v))
}

// DatasetHasSuffix applies the HasSuffix predicate on the "dataset" field.
func DatasetHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldDataset, v))
}

// DatasetEqualFold applies the EqualFold predicate on the "dataset" field.
func DatasetEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldDataset, v))
}

// DatasetContainsFold applies the ContainsFold predicate on the "dataset" field.
func DatasetContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldDataset, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldProvider, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldModel, v))
}

// RequestPathEQ applies the EQ predicate on the "request_path" field.
func RequestPathEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldRequestPath, v))
}

// RequestPathNEQ applies the NEQ predicate on the "request_path" field.
func RequestPathNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldRequestPath, v))
}

// RequestPathIn applies the In predicate on the "request_path" field.
func RequestPathIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldRequestPath, vs...))
}

// RequestPathNotIn applies the NotIn predicate on the "request_path" field.
func RequestPathNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldRequestPath, vs...))
}

// RequestPathGT applies the GT predicate on the "request_path" field.
func RequestPathGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldRequestPath, v))
}

// RequestPathGTE applies the GTE predicate on the "request_path" field.
func RequestPathGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldRequestPath, v))
}

// RequestPathLT applies the LT predicate on the "request_path" field.
func RequestPathLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldRequestPath, v))
}

// RequestPathLTE applies the LTE predicate on the "request_path" field.
func RequestPathLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldRequestPath, v))
}

// RequestPathContains applies the Contains predicate on the "request_path" field.
func RequestPathContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldRequestPath, v))
}

// RequestPathHasPrefix applies the HasPrefix predicate on the "request_path" field.
func RequestPathHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldRequestPath, v))
}

// RequestPathHasSuffix applies the HasSuffix predicate on the "request_path" field.
func RequestPathHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldRequestPath, v))
}

// RequestPathEqualFold applies the EqualFold predicate on the "request_path" field.
func RequestPathEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldRequestPath, v))
}

// RequestPathContainsFold applies the ContainsFold predicate on the "request_path" field.
func RequestPathContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldRequestPath, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldUserAgent, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldStatus, v))
}

// IsFinalSnapshotEQ applies the EQ predicate on the "is_final_snapshot" field.
func IsFinalSnapshotEQ(v bool) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldIsFinalSnapshot, v))
}

// IsFinalSnapshotNEQ applies the NEQ predicate on the "is_final_snapshot" field.
func IsFinalSnapshotNEQ(v bool) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldIsFinalSnapshot, v))
}

// SourceRequestCountEQ applies the EQ predicate on the "source_request_count" field.
func SourceRequestCountEQ(v int) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldSourceRequestCount, v))
}

// SourceRequestCountNEQ applies the NEQ predicate on the "source_request_count" field.
func SourceRequestCountNEQ(v int) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldSourceRequestCount, v))
}

// SourceRequestCountIn applies the In predicate on the "source_request_count" field.
func SourceRequestCountIn(vs ...int) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldSourceRequestCount, vs...))
}

// SourceRequestCountNotIn applies the NotIn predicate on the "source_request_count" field.
func SourceRequestCountNotIn(vs ...int) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldSourceRequestCount, vs...))
}

// SourceRequestCountGT applies the GT predicate on the "source_request_count" field.
func SourceRequestCountGT(v int) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldSourceRequestCount, v))
}

// SourceRequestCountGTE applies the GTE predicate on the "source_request_count" field.
func SourceRequestCountGTE(v int) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldSourceRequestCount, v))
}

// SourceRequestCountLT applies the LT predicate on the "source_request_count" field.
func SourceRequestCountLT(v int) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldSourceRequestCount, v))
}

// SourceRequestCountLTE applies the LTE predicate on the "source_request_count" field.
func SourceRequestCountLTE(v int) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldSourceRequestCount, v))
}

// SystemPromptEQ applies the EQ predicate on the "system_prompt" field.
func SystemPromptEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldSystemPrompt, v))
}

// SystemPromptNEQ applies the NEQ predicate on the "system_prompt" field.
func SystemPromptNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldSystemPrompt, v))
}

// SystemPromptIn applies the In predicate on the "system_prompt" field.
func SystemPromptIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldSystemPrompt, vs...))
}

// SystemPromptNotIn applies the NotIn predicate on the "system_prompt" field.
func SystemPromptNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldSystemPrompt, vs...))
}

// SystemPromptGT applies the GT predicate on the "system_prompt" field.
func SystemPromptGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldSystemPrompt, v))
}

// SystemPromptGTE applies the GTE predicate on the "system_prompt" field.
func SystemPromptGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldSystemPrompt, v))
}

// SystemPromptLT applies the LT predicate on the "system_prompt" field.
func SystemPromptLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldSystemPrompt, v))
}

// SystemPromptLTE applies the LTE predicate on the "system_prompt" field.
func SystemPromptLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldSystemPrompt, v))
}

// SystemPromptContains applies the Contains predicate on the "system_prompt" field.
func SystemPromptContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldSystemPrompt, v))
}

// SystemPromptHasPrefix applies the HasPrefix predicate on the "system_prompt" field.
func SystemPromptHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldSystemPrompt, v))
}

// SystemPromptHasSuffix applies the HasSuffix predicate on the "system_prompt" field.
func SystemPromptHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldSystemPrompt, v))
}

// SystemPromptIsNil applies the IsNil predicate on the "system_prompt" field.
func SystemPromptIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldSystemPrompt))
}

// SystemPromptNotNil applies the NotNil predicate on the "system_prompt" field.
func SystemPromptNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldSystemPrompt))
}

// SystemPromptEqualFold applies the EqualFold predicate on the "system_prompt" field.
func SystemPromptEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldSystemPrompt, v))
}

// SystemPromptContainsFold applies the ContainsFold predicate on the "system_prompt" field.
func SystemPromptContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldSystemPrompt, v))
}

// ToolsIsNil applies the IsNil predicate on the "tools" field.
func ToolsIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldTools))
}

// ToolsNotNil applies the NotNil predicate on the "tools" field.
func ToolsNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldTools))
}

// MessagesIsNil applies the IsNil predicate on the "messages" field.
func MessagesIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldMessages))
}

// MessagesNotNil applies the NotNil predicate on the "messages" field.
func MessagesNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldMessages))
}

// UsageIsNil applies the IsNil predicate on the "usage" field.
func UsageIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldUsage))
}

// UsageNotNil applies the NotNil predicate on the "usage" field.
func UsageNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldUsage))
}

// MetaIsNil applies the IsNil predicate on the "meta" field.
func MetaIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldMeta))
}

// MetaNotNil applies the NotNil predicate on the "meta" field.
func MetaNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldMeta))
}

// SessionJSONIsNil applies the IsNil predicate on the "session_json" field.
func SessionJSONIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldSessionJSON))
}

// SessionJSONNotNil applies the NotNil predicate on the "session_json" field.
func SessionJSONNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldSessionJSON))
}

// PayloadCompressedEQ applies the EQ predicate on the "payload_compressed" field.
func PayloadCompressedEQ(v []byte) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldPayloadCompressed, v))
}

// PayloadCompressedNEQ applies the NEQ predicate on the "payload_compressed" field.
func PayloadCompressedNEQ(v []byte) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldPayloadCompressed, v))
}

// PayloadCompressedIn applies the In predicate on the "payload_compressed" field.
func PayloadCompressedIn(vs ...[]byte) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldPayloadCompressed, vs...))
}

// PayloadCompressedNotIn applies the NotIn predicate on the "payload_compressed" field.
func PayloadCompressedNotIn(vs ...[]byte) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldPayloadCompressed, vs...))
}

// PayloadCompressedGT applies the GT predicate on the "payload_compressed" field.
func PayloadCompressedGT(v []byte) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldPayloadCompressed, v))
}

// PayloadCompressedGTE applies the GTE predicate on the "payload_compressed" field.
func PayloadCompressedGTE(v []byte) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldPayloadCompressed, v))
}

// PayloadCompressedLT applies the LT predicate on the "payload_compressed" field.
func PayloadCompressedLT(v []byte) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldPayloadCompressed, v))
}

// PayloadCompressedLTE applies the LTE predicate on the "payload_compressed" field.
func PayloadCompressedLTE(v []byte) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldPayloadCompressed, v))
}

// PayloadCompressedIsNil applies the IsNil predicate on the "payload_compressed" field.
func PayloadCompressedIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldPayloadCompressed))
}

// PayloadCompressedNotNil applies the NotNil predicate on the "payload_compressed" field.
func PayloadCompressedNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldPayloadCompressed))
}

// PayloadEncodingEQ applies the EQ predicate on the "payload_encoding" field.
func PayloadEncodingEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldPayloadEncoding, v))
}

// PayloadEncodingNEQ applies the NEQ predicate on the "payload_encoding" field.
func PayloadEncodingNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldPayloadEncoding, v))
}

// PayloadEncodingIn applies the In predicate on the "payload_encoding" field.
func PayloadEncodingIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldPayloadEncoding, vs...))
}

// PayloadEncodingNotIn applies the NotIn predicate on the "payload_encoding" field.
func PayloadEncodingNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldPayloadEncoding, vs...))
}

// PayloadEncodingGT applies the GT predicate on the "payload_encoding" field.
func PayloadEncodingGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldPayloadEncoding, v))
}

// PayloadEncodingGTE applies the GTE predicate on the "payload_encoding" field.
func PayloadEncodingGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldPayloadEncoding, v))
}

// PayloadEncodingLT applies the LT predicate on the "payload_encoding" field.
func PayloadEncodingLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldPayloadEncoding, v))
}

// PayloadEncodingLTE applies the LTE predicate on the "payload_encoding" field.
func PayloadEncodingLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldPayloadEncoding, v))
}

// PayloadEncodingContains applies the Contains predicate on the "payload_encoding" field.
func PayloadEncodingContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldPayloadEncoding, v))
}

// PayloadEncodingHasPrefix applies the HasPrefix predicate on the "payload_encoding" field.
func PayloadEncodingHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldPayloadEncoding, v))
}

// PayloadEncodingHasSuffix applies the HasSuffix predicate on the "payload_encoding" field.
func PayloadEncodingHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldPayloadEncoding, v))
}

// PayloadEncodingEqualFold applies the EqualFold predicate on the "payload_encoding" field.
func PayloadEncodingEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldPayloadEncoding, v))
}

// PayloadEncodingContainsFold applies the ContainsFold predicate on the "payload_encoding" field.
func PayloadEncodingContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldPayloadEncoding, v))
}

// PayloadBytesEQ applies the EQ predicate on the "payload_bytes" field.
func PayloadBytesEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldPayloadBytes, v))
}

// PayloadBytesNEQ applies the NEQ predicate on the "payload_bytes" field.
func PayloadBytesNEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldPayloadBytes, v))
}

// PayloadBytesIn applies the In predicate on the "payload_bytes" field.
func PayloadBytesIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldPayloadBytes, vs...))
}

// PayloadBytesNotIn applies the NotIn predicate on the "payload_bytes" field.
func PayloadBytesNotIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldPayloadBytes, vs...))
}

// PayloadBytesGT applies the GT predicate on the "payload_bytes" field.
func PayloadBytesGT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldPayloadBytes, v))
}

// PayloadBytesGTE applies the GTE predicate on the "payload_bytes" field.
func PayloadBytesGTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldPayloadBytes, v))
}

// PayloadBytesLT applies the LT predicate on the "payload_bytes" field.
func PayloadBytesLT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldPayloadBytes, v))
}

// PayloadBytesLTE applies the LTE predicate on the "payload_bytes" field.
func PayloadBytesLTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldPayloadBytes, v))
}

// ExportableEQ applies the EQ predicate on the "exportable" field.
func ExportableEQ(v bool) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldExportable, v))
}

// ExportableNEQ applies the NEQ predicate on the "exportable" field.
func ExportableNEQ(v bool) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldExportable, v))
}

// QualityStatusEQ applies the EQ predicate on the "quality_status" field.
func QualityStatusEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldQualityStatus, v))
}

// QualityStatusNEQ applies the NEQ predicate on the "quality_status" field.
func QualityStatusNEQ(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldQualityStatus, v))
}

// QualityStatusIn applies the In predicate on the "quality_status" field.
func QualityStatusIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldQualityStatus, vs...))
}

// QualityStatusNotIn applies the NotIn predicate on the "quality_status" field.
func QualityStatusNotIn(vs ...string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldQualityStatus, vs...))
}

// QualityStatusGT applies the GT predicate on the "quality_status" field.
func QualityStatusGT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldQualityStatus, v))
}

// QualityStatusGTE applies the GTE predicate on the "quality_status" field.
func QualityStatusGTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldQualityStatus, v))
}

// QualityStatusLT applies the LT predicate on the "quality_status" field.
func QualityStatusLT(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldQualityStatus, v))
}

// QualityStatusLTE applies the LTE predicate on the "quality_status" field.
func QualityStatusLTE(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldQualityStatus, v))
}

// QualityStatusContains applies the Contains predicate on the "quality_status" field.
func QualityStatusContains(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContains(FieldQualityStatus, v))
}

// QualityStatusHasPrefix applies the HasPrefix predicate on the "quality_status" field.
func QualityStatusHasPrefix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasPrefix(FieldQualityStatus, v))
}

// QualityStatusHasSuffix applies the HasSuffix predicate on the "quality_status" field.
func QualityStatusHasSuffix(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldHasSuffix(FieldQualityStatus, v))
}

// QualityStatusEqualFold applies the EqualFold predicate on the "quality_status" field.
func QualityStatusEqualFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEqualFold(FieldQualityStatus, v))
}

// QualityStatusContainsFold applies the ContainsFold predicate on the "quality_status" field.
func QualityStatusContainsFold(v string) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldContainsFold(FieldQualityStatus, v))
}

// QualityErrorsIsNil applies the IsNil predicate on the "quality_errors" field.
func QualityErrorsIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldQualityErrors))
}

// QualityErrorsNotNil applies the NotNil predicate on the "quality_errors" field.
func QualityErrorsNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldQualityErrors))
}

// StorageBytesEQ applies the EQ predicate on the "storage_bytes" field.
func StorageBytesEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldStorageBytes, v))
}

// StorageBytesNEQ applies the NEQ predicate on the "storage_bytes" field.
func StorageBytesNEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldStorageBytes, v))
}

// StorageBytesIn applies the In predicate on the "storage_bytes" field.
func StorageBytesIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldStorageBytes, vs...))
}

// StorageBytesNotIn applies the NotIn predicate on the "storage_bytes" field.
func StorageBytesNotIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldStorageBytes, vs...))
}

// StorageBytesGT applies the GT predicate on the "storage_bytes" field.
func StorageBytesGT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldStorageBytes, v))
}

// StorageBytesGTE applies the GTE predicate on the "storage_bytes" field.
func StorageBytesGTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldStorageBytes, v))
}

// StorageBytesLT applies the LT predicate on the "storage_bytes" field.
func StorageBytesLT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldStorageBytes, v))
}

// StorageBytesLTE applies the LTE predicate on the "storage_bytes" field.
func StorageBytesLTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldStorageBytes, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldOutputTokens, v))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldTotalTokens, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldActualCost, v))
}

// ActualCostIsNil applies the IsNil predicate on the "actual_cost" field.
func ActualCostIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldActualCost))
}

// ActualCostNotNil applies the NotNil predicate on the "actual_cost" field.
func ActualCostNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldActualCost))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldAPIKeyID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldGroupID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldCreatedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotNull(FieldEndedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DataShareSession {
	return predicate.DataShareSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DataShareSession) predicate.DataShareSession {
	return predicate.DataShareSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DataShareSession) predicate.DataShareSession {
	return predicate.DataShareSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DataShareSession) predicate.DataShareSession {
	return predicate.DataShareSession(sql.NotPredicates(p))
}
