#!/usr/bin/env python3
"""在临时 Git 仓库中验证格式化范围和真实 golangci-lint 行为。"""

from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest

from format_go import changed_go_files


PROJECT_ROOT = Path(__file__).resolve().parent.parent
SOURCE = "package sample\n\nvar Value=1\n"
GENERATED = "// Code generated by test. DO NOT EDIT.\n" + SOURCE


class FormatGoTest(unittest.TestCase):
    def setUp(self):
        # 隔离 Git 索引和源码，测试不能格式化真实仓库中的文件。
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        for name in (
            "tools/format_go.py", "tools/golangci-lint.sh",
            "backend/.golangci.yml", ".golangci-version",
        ):
            target = self.root / name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(PROJECT_ROOT / name, target)
        self.git("init", "-q")
        for name in ("unchanged.go", "staged.go", "unstaged.go", "deleted.go", "renamed.go"):
            self.write(name, SOURCE)
        self.write("generated.go", GENERATED)
        self.commit()

    def git(self, *args):
        return subprocess.check_output(["git", "-C", str(self.root), *args])

    def commit(self):
        # 测试身份仅作用于这次命令，不写入用户的 Git 配置。
        self.git("add", ".")
        self.git("-c", "user.name=Formatter Test", "-c", "user.email=test@example.invalid",
                 "-c", "commit.gpgsign=false", "commit", "-qm", "test: fixture")

    def write(self, name, source):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source)

    def run_formatter(self, *args):
        return subprocess.run(
            [sys.executable, str(self.root / "tools/format_go.py"), *args],
            cwd=self.root, capture_output=True, text=True,
        )

    def test_selection_and_index_preservation(self):
        self.write("staged.go", SOURCE + "var Staged=2\n")
        self.git("add", "staged.go")
        staged = self.git("show", ":staged.go")
        self.write("staged.go", SOURCE + "var Unstaged=3\n")
        self.write("unstaged.go", SOURCE + "var Other=4\n")
        self.git("mv", "renamed.go", "with space.go")
        (self.root / "deleted.go").unlink()
        self.write("new\nfile.go", SOURCE)
        self.write("backend/ent/schema/item.go", SOURCE)
        self.write("generated.go", GENERATED + "var Generated=2\n")
        self.write("new_generated.go", GENERATED)
        self.write("vendor/dependency.go", SOURCE)
        self.write("node_modules/dependency.go", SOURCE)
        (self.root / "linked.go").symlink_to("unchanged.go")
        self.write(".gitignore", "ignored.go\n")
        self.write("ignored.go", SOURCE)

        selected = {str(path.relative_to(self.root)) for path in changed_go_files(self.root)}
        self.assertEqual(selected, {
            "staged.go", "unstaged.go", "with space.go", "new\nfile.go",
            "backend/ent/schema/item.go",
        })
        before = {path: path.read_bytes() for path in self.root.rglob("*.go") if path.is_file()}
        result = self.run_formatter("--check")
        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertTrue(all(path.read_bytes() == content for path, content in before.items()))
        result = self.run_formatter()
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(self.git("show", ":staged.go"), staged)
        for path, content in before.items():
            if str(path.relative_to(self.root)) not in selected:
                self.assertEqual(path.read_bytes(), content)
        result = self.run_formatter("--check")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_clean_checkout_uses_commit_base(self):
        base = self.git("rev-parse", "HEAD").decode().strip()
        self.write("committed.go", SOURCE)
        self.write("committed_generated.go", GENERATED)
        self.commit()
        self.assertEqual(self.git("status", "--porcelain"), b"")
        self.assertEqual(changed_go_files(self.root), [])
        self.assertEqual(changed_go_files(self.root, base), [self.root / "committed.go"])
        result = self.run_formatter("--check", "--base", base)
        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertEqual(self.git("status", "--porcelain"), b"")

    def test_shared_gofmt_rewrites_and_gofumpt_defaults(self):
        self.write("rules.go", """package sample

func convert(values []int, offset int) interface{} {

    return values[offset:len(values)]

}

func names(first string, second string) {}
""")
        result = self.run_formatter()
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        formatted = (self.root / "rules.go").read_text()
        self.assertIn(") any {\n\treturn values[offset:]\n}", formatted)
        # 默认规则不合并同类型参数，防止误开启 extra。
        self.assertIn("func names(first string, second string)", formatted)
        result = self.run_formatter("--check")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_invalid_base_and_wrong_tool_version_fail(self):
        result = self.run_formatter("--check", "--base", "missing-ref")
        self.assertNotEqual(result.returncode, 0)
        self.write("new.go", SOURCE)
        self.write(".golangci-version", "v0.0.0\n")
        result = self.run_formatter()
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual((self.root / "new.go").read_text(), SOURCE)

    def test_full_lint_exclusion_keeps_incremental_format_check(self):
        # 全量 lint 可以接受历史空行，但改动文件的格式检查必须仍然报错。
        self.write("lintfixture/go.mod", "module example.com/formatfixture\n\ngo 1.27.0\n")
        self.write("lintfixture/value.go", "package sample\n\nfunc Read() int {\n\n\treturn 1\n\n}\n")
        result = subprocess.run(
            ["bash", str(self.root / "tools/golangci-lint.sh"), "run",
             "--config", str(self.root / "backend/.golangci.yml"), "--timeout=2m", "./..."],
            cwd=self.root / "lintfixture", capture_output=True, text=True,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        result = self.run_formatter("--check")
        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)


if __name__ == "__main__":
    unittest.main()
